### PR TITLE
add kubectl-ai plugin

### PR DESCRIPTION
**Pull request by sozercan**
adds https://github.com/sozercan/kubectl-ai plugin to krew index

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Thanks for the submission. I think the name "ai" takes advantage of being a first-comer. Typically we try not to assign broad terms to any particular plugin.

By assigning this name, it basically takes the opportunity from all and every AI related plugin to kubectl. Hope that makes sense. 

A recently added relevant plugin was called "kopilot" and that was unique enough that it didn't warrant this discussion. 

So if it's not too late, I recommend a more relevant name, like "ai-example" that can also explain the functionality better. You can also always host a custom plugin index to distribute it yourself more freely.

**Comment by sozercan** [comment]
@ahmetb thanks! that makes sense. would repo or binary name have to match the plugin metadata name? for example, plugin name being `ai-example` or similar, while binary name as `kubectl-ai`.

**Comment by ahmetb** [comment]
Repo name or the executable name in the tar/zip archive does not have to match to the `name:` field in the plugin manifest, but the `name` field determines how the symlink is created (and therefore how the plugin is invoked).

We have quite a few plugins that act both as a standalone tool as well as a kubectl plugin (or plugins that have a different name in krew), and they print the right usage/--help outputs based on the invocation method.

**Pull request closed without merging**
