### PR TITLE
Add nodeinfo plugin

### PR DESCRIPTION
**Pull request by giorgosdi**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by giorgosdi** [comment]
Hello 👋 , its my first time adding a plugin here and I think that I might need some help.
It looks like the extraction fails for some reason,any help is appreciated 😃

**Comment by giorgosdi** [comment]
Disregard my previous comment. The tarballs are fixed now 🔧

**Comment by giorgosdi** [comment]
Hey @ahmetb , sorry for the direct mention but i didnt want this PR to be lost between the daily workloads that you guys have as maintainers. Is there anything else I can do on my side to make this PR approvable ?

**Comment by ahmetb** [comment]
Trying out and got:

```
/Users/ahmet/.kube/twconfig:/Users/ahmet/.kube/twconfig
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4f365c9]

goroutine 1 [running]:
k8s.io/client-go/kubernetes.NewForConfig(0x0)
	/Users/giorgos.dimitriou/go/pkg/mod/k8s.io/client-go@v0.23.3/kubernetes/clientset.go:414 +0x29
github.com/giorgosdi/nodeinfo/pkg/auth.GetClients({0xc00004800b, 0xc0003dd2d0})
	/Users/giorgos.dimitriou/personal/nodeinfo/pkg/auth/auth.go:11 +0x32
github.com/giorgosdi/nodeinfo/pkg/cmd.getInfo(0xc0003bac00, 0xc0003bac00, {0x63bd428, 0x0, 0x0})
	/Users/giorgos.dimitriou/personal/nodeinfo/pkg/cmd/nodeinfo.go:51 +0x29
github.com/giorgosdi/nodeinfo/pkg/cmd.NewNodeInfoCommand.func1(0xc000420280, {0x63bd428, 0x0, 0x0})
	/Users/giorgos.dimitriou/personal/nodeinfo/pkg/cmd/nodeinfo.go:40 +0x65
github.com/spf13/cobra.(*Command).execute(0xc000420280, {0xc00003c1e0, 0x0, 0x0})
	/Users/giorgos.dimitriou/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc000420280)
	/Users/giorgos.dimitriou/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/giorgos.dimitriou/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/giorgosdi/nodeinfo/cmd.KubectlNodeinfo()
	/Users/giorgos.dimitriou/personal/nodeinfo/cmd/kubectl-nodeinfo.go:31 +0xf6
main.main()
	/Users/giorgos.dimitriou/personal/nodeinfo/main.go:23 +0x17
```

**Comment by giorgosdi** [comment]
Thanks for taking a look 💪  ! Fixed the above, it needed some more graceful error handling. There is more to come in future releases

**Comment by ahmetb** [comment]
FWIW there are still issues. e.g. when I use multiple kubeconfigs in KUBECONFIG env var, it thinks they're the same file.

    stat /Users/ahmet/.kube/config:/Users/ahmet/.kube/myconfig: no such file or directory

**Comment by ahmetb** [comment]
So the metrics API is disabled on my local cluster but I got it to work and I'm afraid the functionality of this plugin is already a subset of other plugins like `resource-capacity` or `view-allocations`. These plugins are already capable of showing per-node allocation and it seems like adding your plugin currently will be redundant.

That said, you can still distribute your plugin via Krew using custom indexes: https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes/ That way users can still install your plugin via Krew, but they'll be downloading the plugin manifest from your repository instead of krew-index.

/hold

**Comment by giorgosdi** [comment]
Hey Ahmet, thanks for your quick response man.

I havent use more than one kubeconfig paths at a time so thats news to me, didnt know that this can be done.

I have looked at the two plugins you are referring to. Frankly I dont see enough similarities with `view-allocations` other than this is also a plugin that outputs resource metrics, in a different manner though.

I do however see how `resource-capacity` does this job in one way or the other.

Feel free to close the PR (or let me know so i can close it, dont know how the process works here)

**Comment by ahmetb** [comment]
Thanks for taking the feedback. 
As you can understand, plugins with identical functionality is not great for the curation here. 

You can still distribute your plugin via Krew using custom indexes: https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes/ That way users can still install your plugin via Krew, but they'll be downloading the plugin manifest from your repository instead of krew-index. 

/close

**Pull request closed without merging**
