### PR TITLE
bump kubectl-neat to v2.0.2

### PR DESCRIPTION
**Pull request by itaysk**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/neat.yaml is not a straightforward version bump: no 'uri:' field changes done in the patch

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/neat.yaml is not a straightforward version bump: no 'uri:' field changes done in the patch

**Comment by corneliusweig** [comment]
It looks like you forgot to adjust the version number in the URL. Maybe you want to automate the release with [krew-release-bot](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/)?

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request seems to straightforward.
I'll go ahead and accept it. :+1: Cheers.

/lgtm
/approve

**Comment by itaysk** [comment]
@corneliusweig yes, thanks.. It's semi-automatic but as we can see still error prone. I will look into better automation :)

**Pull request merged**
