### PR TITLE
Eksporter v1.3.0 release

### PR DESCRIPTION
**Pull request by Kyrremann**
Will now also remove clusterIP from resources.

Fixes https://github.com/Kyrremann/kubectl-eksporter/issues/3

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/eksporter.yaml is not a straightforward version bump: changing old version ("1.1.0") with new version ("1.3.0") in the url (https://github.com/Kyrremann/kubectl-eksporter/releases/download/v1.2.0/eksporter.tar.gz) does not appear in the patch as https://github.com/Kyrremann/kubectl-eksporter/releases/download/v1.2.0/eksporter.tar.gz

**Comment by Kyrremann** [comment]
Hopefully this will be fixed in the next version, since I forgot to bump version last time.

> file plugins/eksporter.yaml is not a straightforward version bump: changing old version ("1.1.0") with new version ("1.3.0") in the url (https://github.com/Kyrremann/kubectl-eksporter/releases/download/v1.2.0/eksporter.tar.gz) does not appear in the patch as https://github.com/Kyrremann/kubectl-eksporter/releases/download/v1.2.0/eksporter.tar.gz

**Comment by ahmetb** [comment]
@Kyrremann would you consider using https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/ in the future?

/lgtm
/approve

**Comment by Kyrremann** [comment]
Did not know about that one! Will set that up. Thank you.

**Pull request merged**
