### PR TITLE
update direct-csi v1.4.4

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/direct-csi.yaml` is not a straightforward version bump: change on line `3` does not seem like a version bump: [`-        os: linux`]

**Comment by ahmetb** [comment]
@harshavardhana 

> 	W1109 18:11:29.123919    2646 install.go:164] failed to install plugin "direct-csi": install failed: failed to link installed plugin: can't create symbolic link, source binary ("/tmp/krew-test201076024/store/direct-csi/v1.4.4/kubectl-direct_csi.exe") cannot be found in extracted archive: stat /tmp/krew-test201076024/store/direct-csi/v1.4.4/kubectl-direct_csi.exe: no such file or directory

Please make sure this installs correctly on windows (you can override with KREW_OS=windows and try installing locally).

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/direct-csi.yaml` is not a straightforward version bump: change on line `3` does not seem like a version bump: [`-        os: linux`]

**Comment by harshavardhana** [comment]
> KREW_OS=windows

Done @ahmetb

**Comment by ahmetb** [comment]
/lgtm
/approve

Also, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

**Pull request merged**
