### PR TITLE
bulk-action plugin update

### PR DESCRIPTION
**Pull request by emreodabas**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/bulk-action.yaml is not a straightforward version bump: version should have metadata ("beta"), only no pre-release versions are auto-approved

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/bulk-action.yaml is not a straightforward version bump: version should have metadata ("beta"), only no pre-release versions are auto-approved

**Comment by emreodabas** [comment]
I updated my email for git commit

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/bulk-action.yaml is not a straightforward version bump: diff line 16 unrecognized for version bumps: [-        - from: kubectl-plugins-*/kubectl-bulk]

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/bulk-action.yaml is not a straightforward version bump: diff line 16 unrecognized for version bumps: [-        - from: kubectl-plugins-*/kubectl-bulk]

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/bulk-action.yaml is not a straightforward version bump: changing old version ("1.1.0-beta") with new version ("1.1.1") in the url (https://github.com/emreodabas/kubectl-plugins/archive/v1.1.0-beta.tar.gz) does not appear in the patch as https://github.com/emreodabas/kubectl-plugins/archive/v1.1.1.tar.gz

**Comment by corneliusweig** [comment]
@emreodabas You closed the PR, but assigned me. Do you want to revive it?

**Comment by emreodabas** [comment]
I confused this with my other PR request. Sorry for the confusion.

**Comment by corneliusweig** [comment]
Me too, didn't see the other PR :)

**Pull request closed without merging**
