### PR TITLE
Update virt (KubeVirt virtctl plugin package) to v0.21.0

### PR DESCRIPTION
**Pull request by dhiller**
See https://github.com/kubevirt/kubevirt/releases/tag/v0.21.0

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **doesn't** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/virt.yaml is not a straightforward version bump: diff line unrecognized for version bumps: [-        - from: "/virtctl/virtctl-v0.20.4-darwin-amd64"]

**Comment by dhiller** [comment]
@ahmetb can you please elaborate on what the robot meant, I don't understand why this is not a straightforward version bump? Thanks!

**Comment by ahmetb** [comment]
This is happening because your filename _also_ contains version.

In a straightforward version bump, we only expect `uri` `version` and `sha256` fields to change. If you fix your releases to use a static filename for the executable, your PRs can be automatically merged. Wanna try that?

**Comment by ahmetb** [comment]
For example: https://patch-diff.githubusercontent.com/raw/kubernetes-sigs/krew-index/pull/206.patch

**Comment by dhiller** [comment]
Will do. Might take some time though.

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **doesn't** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/virt.yaml is not a straightforward version bump: diff line unrecognized for version bumps: [-        - from: "/virtctl/virtctl-v0.20.4-darwin-amd64"]

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **doesn't** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/virt.yaml is not a straightforward version bump: diff line unrecognized for version bumps: [-        - from: "/virtctl/virtctl-v0.20.4-darwin-amd64"]

**Comment by dhiller** [comment]
@ahmetb hopefully got it right this time :)

**Comment by ahmetb** [comment]
:) this one will require manual approval since the overall diff had a change in `from:` line. hopefully, next one will be approved automatically.
/lgtm
/approve

**Pull request merged**
