### PR TITLE
new version v0.1.0 of etcdviewer

### PR DESCRIPTION
**Pull request by double12gzh**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Hi, can you please explain why you submit this a kubectl plugin and not have it just be a standalone tool?

As far as I can tell, this directly interacts with etcd and doesn't have much with Kubernetes API? (E.g. can't work on cloud clusters where etcd is hidden)

**Comment by double12gzh** [comment]
> Hi, can you please explain why you submit this a kubectl plugin and not have it just be a standalone tool?
> 
> As far as I can tell, this directly interacts with etcd and doesn't have much with Kubernetes API? (E.g. can't work on cloud clusters where etcd is hidden)

Great thanks for your reply. 

Yes, it doesn't have much with k8s API，excpet using k8s runtime tools to encode/decode k8s data stored in etcd. 
My purpose at the begining was to deliver this plugin only for k8s users' only, so it can be installed and used conveninently.

**Comment by ahmetb** [comment]
We expect kubectl plugins to complement or extend kubectl/Kubernetes experience. This might be more of an etcdctl companion, hence not a good fit for here.

**Comment by double12gzh** [comment]
gg

> We expect kubectl plugins to complement or extend kubectl/Kubernetes experience. This might be more of an etcdctl companion, hence not a good fit for here.

Cool, I accept.

**Pull request closed without merging**
