### PR TITLE
release new version v0.8.0 of eds

### PR DESCRIPTION
**Pull request by L3n41c**
Update the version of the [`eds` krew plugin to `v0.8.0`](https://github.com/DataDog/extendeddaemonset/releases/tag/v0.8.0)

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this. If we don't respond within a day, feel free to ping us.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/eds.yaml` is not a straightforward version bump: change on line `4` does not seem like a version bump: [`-  shortDescription: Interact and manage ExtendedDaemonset resources`]
/kind plugin-update

**Comment by ahmetb** [comment]
please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

/lgtm

**Comment by L3n41c** [comment]
Hi @ahmetb,
Thanks for the hint about the GH workflow bot.
It turns out that [it should already be setup](https://github.com/DataDog/extendeddaemonset/blob/v0.8.0/.github/workflows/release.yaml#L63-L68).
The release workflow of the CI says that [the step worked well](https://github.com/DataDog/extendeddaemonset/actions/runs/1707182324/jobs/2332552239). But unfortunately, it ran such a long time ago that the logs have been deleted.
I fear that we’ll need to wait for the next release to check if something is mis-configured. Because [that workflow worked for previous release](https://github.com/kubernetes-sigs/krew-index/pull/1522), so I have no clue what failed for this specific release.

**Pull request merged**
