### PR TITLE
add kubectl plugin - kruise

### PR DESCRIPTION
**Pull request by hantmac**
Signed-off-by: hantmac <hantmac@outlook.com>

Add kubectl kruise for [OpenKruise](https://openkruise.io/). And has verified by `kubectl krew install --manifest`.

### CODE REVIEW

**Comment by ahmetb** [comment]
@hantmac thanks for the submission.

1. Is this tool advertised as a kubectl plugin in the product's documentation as well, or is this normally a standalone tool that you've packaged here?
2. Are you one of the maintainers of the plugin? Otherwise, can the plugin maintainers set up automation (e.g. https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) so that the krew-index is kept up to date with the latest versions?

**Comment by hantmac** [comment]
> @hantmac thanks for the submission.
> 
> 1. Is this tool advertised as a kubectl plugin in the product's documentation as well, or is this normally a standalone tool that you've packaged here?
> 2. Are you one of the maintainers of the plugin? Otherwise, can the plugin maintainers set up automation (e.g. https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) so that the krew-index is kept up to date with the latest versions?

Thanks for your reply.
1. This tool is advertised as a kubectl plugin in the product's documentation, [here](https://openkruise.io/docs/next/cli-tool/kubectl-plugin/)
2. I am a maintainer of the OpenKruise project, also this plugin.

**Comment by hantmac** [comment]
@ahmetb Hi, would you like to help me review & merge this PR?

**Comment by ahmetb** [comment]
Truly my apologies. I have forgotten. 
/lgtm
/approve
Thanks!

**Pull request merged**
