### PR TITLE
add interact-sh plugin

### PR DESCRIPTION
**Pull request by ya-makariy**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
The idea of the plugin is lgtm. 

Unrelated comment about the plugin itself: I highly recommend you use something like `fzf` to shell out to. :) That's what I do in kubectx and it saves a ton of work. The current interactive picker you have is actually a lot slower than typing out the names by hand or using kubectl shell completion. I found it very difficult to use and scroll down the list etc.

**Comment by ahmetb** [comment]
Oh and I think you have a bug that doesn't parse multiple containers in a Pod onto different lines, so I ended up choosing a line with both container names in one line and as a result could not get this to work.

**Comment by ya-makariy** [comment]
Thanks for the quick response. I will change the scroll mechanism to speed up the whole process. And then I'll be back)

yep, it was a bug)

**Comment by ya-makariy** [comment]
Hey @ahmetb, could you review the plugin again?

**Pull request closed without merging**
