### PR TITLE
Add kubectl-safe

### PR DESCRIPTION
**Pull request by rumstead**
This plugin allows users to confirm when they get prompted on certain kubectl commands.

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Is it fair to compare this to [prompt](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/prompt.yaml) plugin?

**Comment by ahmetb** [comment]
No need to close this?

**Comment by rumstead** [comment]
> Is it fair to compare this to [prompt](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/prompt.yaml) plugin?

They are very similar. The main difference I can see is the granularity at which you get prompts. It also doesn't require bash.

**Comment by ahmetb** [comment]
/lgtm
/approve
Thanks!
Also, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

**Pull request merged**
