### PR TITLE
Add node allocations plugin

### PR DESCRIPTION
**Pull request by wshihadeh**
PLUGIN DEVELOPERS: @wshihadeh

Hi Team,

I would like to add my new plugin

Thanks
Al-waleed

### CODE REVIEW

**Comment by ahmetb** [comment]
Is the output below (showing how many nodes are there on each node) all this plugin does?

```
kubectl node-allocations --all-namespaces
NODE                                               PODS-COUNT
gk3-autopilot-cluster-nap-1nafw4xe-26a7899f-k0ad   11
gk3-autopilot-cluster-default-pool-eeb737f6-uy2z   14
```

If so, I am afraid there's not enough utility to warrant adding it here.
Furthermore, I think the name is not great –node allocation in Kubernetes context typically refer to how the resources like CPU/memory are reserved to the system vs the dynamic workloads. (e.g. see the definition [here](https://unofficial-kubernetes.readthedocs.io/en/latest/tasks/administer-cluster/reserve-compute-resources/)).

**Comment by wshihadeh** [comment]
Yes that is the first command currently implemented (show pods count by Node), However I am going to add more commands and features

**Comment by corneliusweig** [comment]
IMO `statistics` is far too generic, so that's a no-go for me.

My impression is that the plugin is still heavy in the conception phase. As of right now, the added functionality is low, so I'm reluctant to merge already. I'd encourage you to add more functionality and then let's reconsider. Please be aware that it is not great to have too much overlap with existing plugins, so please have a look at the existing plugins https://krew.sigs.k8s.io/plugins/.

/kind gray-area
/hold

**Comment by ahmetb** [comment]
+1 for revisiting later. 

Until then, you can still distribute your plugin via Krew using custom indexes: https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes/ That way users can still install your plugin via Krew, but they'll be downloading the plugin manifest from your repository instead of krew-index. 

/close

**Pull request closed without merging**
