### PR TITLE
Remove redundant information from `caveats`

### LINKED ISSUE #367: Remove usage and homepage from `caveats` section
Many plugin manifests include usage information and links to the plugin homepage in their `caveats` section. To make this more uniform, `krew` now prints this information by default after plugin installs (https://github.com/kubernetes-sigs/krew/issues/402). This change will be part of next krew release (>v0.3.2).

After releasing the next krew version, we should remove this obsolete information from all plugin manifests.

### PR DESCRIPTION
**Pull request by corneliusweig**
Krew shows homepage and how to call the plugin by default after install.
Many plugins used to put these instructions into their caveats section,
but this is redundant now. This PR cleans up the manifests. The
`caveats` section is now really reserved for dependency information or
warnings.

Close #367

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/bulk-action.yaml is not a straightforward version bump: could not find the old/new version spec in the diff

**Comment by ahmetb** [comment]
What do we do about automated PRs?
Notify them to fix them in the upstream once those PRs come (and get not automerged)? Or did you take those into account?

/lgtm
/approve
/hold
Feel free to unhold anytime

**Comment by corneliusweig** [comment]
No, I didn't take care of manifest templates in upstream repos. That would simply not scale well. Even though it will delay the releases of new versions for a while, I think it's okay to request these amendments from our contributors.

**Comment by ahmetb** [comment]
```
I0601 10:33:48.505817    5300 main.go:66] reading file plugins/tail.yaml
F0601 10:33:48.506072    5300 main.go:61] failed to read plugin file: failed to decode plugin manifest: error converting YAML to JSON: yaml: line 41: mapping values are not allowed in this context
```

seems to be the current blocker.

**Comment by corneliusweig** [comment]
Interesting. There was a YAML syntax issue which was silently ignored until now. Looks like `-|` is less forgiving than `|-` :)

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/bulk-action.yaml is not a straightforward version bump: could not find the old/new version spec in the diff

**Pull request merged**
