### PR TITLE
Adds darwin support for whisper-secret

### PR DESCRIPTION
**Pull request by rewanthtammana**
Hi @corneliusweig @ahmetb ,

Change log of this PR:

* Adds darwin support for whisper-secret
* I changed my GitHub username. It replaces the links.
* Updates version
* Minor tweak to example in description section

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/whisper-secret.yaml` is not a straightforward version bump: change on line `0` does not seem like a version bump: [`-apiVersion: krew.googlecontainertools.github.com/v1alpha2`]

**Comment by corneliusweig** [comment]
/lgtm
/approve
Thanks!

**Comment by rewanthtammana** [comment]
Closes https://github.com/rewanthtammana/kubectl-whisper-secret/issues/1

**Pull request merged**
