### PR TITLE
[minio/direct-csi] Update version to v1.1.0 and windows/darwin support

### PR DESCRIPTION
**Pull request by wlan0**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/direct-csi.yaml is not a straightforward version bump: diff line 7 unrecognized for version bumps: [+    bin: kubectl-direct_csi]

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/direct-csi.yaml is not a straightforward version bump: diff line 7 unrecognized for version bumps: [+    bin: kubectl-direct_csi]

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/direct-csi.yaml is not a straightforward version bump: diff line 7 unrecognized for version bumps: [+    bin: kubectl-direct_csi]

**Comment by wlan0** [comment]
Thanks @ahmetb!

**Pull request merged**
