### PR TITLE
Bump oidc-login to v1.15.2

### PR DESCRIPTION
**Pull request by fcuello-fudo**
CC @int128

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request seems to be a straightforward version bump.
I'll go ahead and accept it. :+1: Cheers.

/lgtm
/approve

**Comment by int128** [comment]
@fcuello-fudo Thank you so much! I just forgot creating a pull request for v1.15.2.

**Comment by inductor** [comment]
@fcuello-fudo Hello! As the CI bot says, you need to sign CLA to get this PR merged.
Note that your Linux Foundation registration should be matched to your commit information.

**Comment by fcuello-fudo** [comment]
> @fcuello-fudo Hello! As the CI bot says, you need to sign CLA to get this PR merged.
> Note that your Linux Foundation registration should be matched to your commit information.

Done!

**Pull request merged**
