### PR TITLE
Add mdba plugin manifest

### PR DESCRIPTION
**Pull request by hedgieinsocks**
```bash
❯ k krew install --manifest=./plugins/mdba.yaml
Installing plugin: mdba
Installed plugin: mdba
\
 | Use this plugin:
 |      kubectl mdba
 | Documentation:
 |      https://github.com/hedgieinsocks/kubectl-mdba
 | Caveats:
 | \
 |  | Dependencies: jq
 | /
/
```

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
The only concern I have is with the name of the plugin. It is not an official plugin of mariadb project -and as I understand it doesn’t support all mariadb clusters, but it grabs the generic popular name of “mdb”. Am I right in this assessment?

**Comment by hedgieinsocks** [comment]
Yes, your assessment is correct. 

Since not every krew user will go to the repo to see the disclaimer, I can try to better indicate in the manifest that it's unofficial and has limited functionality. 

As for taking the `mdb` name, I understand your point. Although, they don't seem to have any plans to create an official plugin in the observable future, that could easily change.

If you would like me to choose another name, I'll surely do that. Just need to come up with a good new one))

**Comment by ahmetb** [comment]
/lgtm
/approve
Thanks!
Also, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

**Pull request merged**
