### PR TITLE
Add chainsaw plugin

### PR DESCRIPTION
**Pull request by eddycharly**
Add chainsaw plugin.

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Thanks for the submission. Can you help me understand why you want to distribute this as a kubectl plugin and not as a standalone tool?

Typically we expect kubectl plugins to improve the kubectl experience or add supplementing resource/cluster management functionality to kubectl.

**Comment by eddycharly** [comment]
> Thanks for the submission. Can you help me understand why you want to distribute this as a kubectl plugin and not as a standalone tool?

Chainsaw is already available as a standalone tool. It is definitely a kubernetes tool though, as the sole purpose of chainsaw is to run operators e2e tests.

> Typically we expect kubectl plugins to improve the kubectl experience or add supplementing resource/cluster management functionality to kubectl.

Chainsaw is a testing related plugin. I feel like it makes sense to distribute it as a plugin, It is very similar in spirit as the kuttl plugin (chainsaw was inspired by kuttl at the beginning).

Users using chainsaw will also use `kubectl` extensively. Having a chainsaw plugin will streamline the user experience by making everything available through `kubectl`.

**Comment by ahmetb** [comment]
Ideally we don't package every single tool in Kubernetes ecosystem as a kubectl plugin. Minikube or kind are good examples to that. Setting existing precedent of kuttl aside, I'm not sure dependency of the tool on kubectl is a solid rationale here.

**Comment by eddycharly** [comment]
Up to you, I thought it would make the migration from kuttl to chainsaw easier, especially for users that are used to work with the kuttl plugin.

Feel free to close this PR if you think it's not a relevant submission.

**Comment by eddycharly** [comment]
As an example, I'm currently helping Keptn folks to migrate from kuttl to chainsaw and they use the kuttl plugin extensively https://github.com/keptn/lifecycle-toolkit/blob/64431370efd06aafcfe37b41d0121b69dd751ebf/Makefile#L34-L37 in their CI pipeline and locally.

That's why i had the idea to submit a chainsaw plugin, to bring similar experience.

**Comment by realshuting** [comment]
I use Chainsaw to run e2e tests in Kubernertes and it works like a charm. Would love to see this be accepted as a Kubectl plugin for easier access and upgrade!

**Comment by Sanskarzz** [comment]
Chainsaw has been my go-to tool for conducting end-to-end tests within Kubernetes, and its performance has been stellar. It would be fantastic if this could be integrated as a Kubectl plugin for more seamless access .

**Comment by ahmetb** [comment]
These last two comments can be made for Homebrew packaging as well. I don't think they're reasons for packaging the executable in a curated kubectl plugin registry. I appreciate if someone can explain how it makes kubectl experience better.

**Comment by eddycharly** [comment]
> These last two comments can be made for Homebrew packaging as well

Indeed, and we are already releasing on brew.

> I appreciate if someone can explain how it makes kubectl experience better

Chainsaw is a tool to test kubernetes operators, users will use kubectl to troubleshoot and investigate failures all the time.

The plugin would allow doing everything in kubectl directly without the need to jump from one tool to the other.

Also, as others mentioned it will help distributing and updating chainsaw.

Not sure if will _make kubectl experience better_ but for sure it will make users life easier. For a tool that is kubernetes centric it makes sense to have the plugin option to me.

**Pull request closed without merging**
