### PR TITLE
Fix a typo in caveats of iexec

### PR DESCRIPTION
**Pull request by ferhatelmas**
/cc @gabeduke

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **doesn't** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/iexec.yaml is not a straightforward version bump: could not find the old/new version spec in the diff

**Comment by gabeduke** [comment]
Thanks good find!

**Comment by ahmetb** [comment]
We actually now show `homepage:` field after installation. so this is actually redundant to begin with.

**Comment by gabeduke** [comment]
Oh cool I'll update

**Pull request merged**
