### PR TITLE
Add kubeaudit to krew plugins

### PR DESCRIPTION
**Pull request by selfcommit**
Submitted on behalf of Shopify, to complete https://github.com/Shopify/kubeaudit/issues/331

Related license is available here:
https://github.com/Shopify/kubeaudit/blob/main/LICENSE

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Can you read the discussion on #2924 about standalone tools with kube prefix being distributed as plugins? (In this case, "audit" name is a bit too generic to assign to a particular plugin.)

Also, we expect plugin authors to submit these addition requests as it would require them to fix the -help message to show the right usage when invoked as a kubectl plugin, set up release automation etc.

**Comment by selfcommit** [comment]
Thanks @ahmetb -

I've left a request with the plugin author to add releast automation / respond back to this thread.
(I'm responding to an open issue on their project, thus not a direct maintainer)

Regarding the name:
`kubeaudit` seems to be an established name for the tool at Shopify.

After reading through #2924 it seems the rub is having the `kube` prefix?

I agree `audit` is too broad, but as the first result returned when searching for`kubeaudit` is the Shopify project, it might make sense to keep `kubeaudit` here.

**Comment by ahmetb** [comment]
I think some questions still remain:

- do you think this tool benefits from being a kubectl plugin, in addition to being a standalone tool?

- does this feel like something that'd be potentially part of kubectl (or a better alternative to something in kubectl) like other plugins are? (I assume yes)

- will the tool work like a kubectl plugin when run as such (e.g. print proper usage strings in its examples or -help messages)?

**Comment by ahmetb** [comment]
Hi, sorry for the delay here. Do the authors of the tool commit to distributing this tool as a kubectl plugin as well (in addition to being a standalone tool), and keep the versions updated here? Ideally we expect tool authors to do the plugin submissions indicating they are doing this as a supported means of distribution.
/hold

**Comment by ahmetb** [comment]
/close
Feel free to resubmit if authors agree on maintaining a release as a kubectl plugin.

**Pull request closed without merging**
