### PR TITLE
[minio/direct-csi] Update version to v3.1.0

### PR DESCRIPTION
**Pull request by Praveenrajmani**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this. If we don't respond within a day, feel free to ping us.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/direct-csi.yaml` is not a straightforward version bump: changing old version (`"3.0.4"`) with new version (`"3.1.0"`) in the url (`https://github.com/minio/direct-csi/releases/download/v3.0.3/kubectl-direct_csi_windows_amd64.zip`) does not appear in the patch as `https://github.com/minio/direct-csi/releases/download/v3.0.3/kubectl-direct_csi_windows_amd64.zip`
/kind plugin-update

**Comment by Praveenrajmani** [comment]
> robot _Beep beep! I’m a robot speaking on behalf of @ahmetb._ robot
> 
> This pull request **does not** seem to be a straightforward version bump. I'll have a human review this. If we don't respond within a day, feel free to ping us.
> 
> _Why wasn't this detected as a plugin version bump:_
> 
> > file `plugins/direct-csi.yaml` is not a straightforward version bump: changing old version (`"3.0.4"`) with new version (`"3.1.0"`) in the url (`https://github.com/minio/direct-csi/releases/download/v3.0.3/kubectl-direct_csi_windows_amd64.zip`) does not appear in the patch as `https://github.com/minio/direct-csi/releases/download/v3.0.3/kubectl-direct_csi_windows_amd64.zip`
> > /kind plugin-update

looks like the windows image wasn't updated properly last time

**Comment by Praveenrajmani** [comment]
PTAL @ahmetb @corneliusweig

**Comment by ahmetb** [comment]
Is there a reason why you aren’t using the krew release automation and avoid these issues altogether and save manual review efforts?

**Comment by ahmetb** [comment]
/lgtm
/approve
Also, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

**Pull request merged**
