### PR TITLE
Bump  KUDO to v0.14.0

### PR DESCRIPTION
**Pull request by kensipe**
Signed-off-by: Ken Sipe <kensipe@gmail.com>

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request seems to straightforward.
I'll go ahead and accept it. :+1: Cheers.

/lgtm
/approve

**Comment by ahmetb** [comment]
tests failing PTAL.

**Comment by ahmetb** [comment]
Actually I'm not sure why github has returned text/plain for these .tar.gz files. Can you push an empty commit?

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request seems to straightforward.
I'll go ahead and accept it. :+1: Cheers.

/lgtm
/approve

**Comment by kensipe** [comment]
@ahmetb strange... thoughts?

**Comment by ahmetb** [comment]
@kensipe pls read the error(s).
https://github.com/kudobuilder/kudo/releases/download/v0.14.0/kudo_0.14.0_darwin_i386.tar.gz
returns 404.

**Comment by kensipe** [comment]
yikes.. my bad... something must have changed on our end... back in a few

**Comment by corneliusweig** [comment]
@kensipe What's the status about the failed download, should it work already? You can retrigger the CI by pushing to this branch (even if it's an empty commit).
/retest

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/kudo.yaml is not a straightforward version bump: diff line 5 unrecognized for version bumps: [-    bin: "./kubectl-kudo"]

**Comment by kensipe** [comment]
@ahmetb sorry for delays...  we don't release or support 32 bit Darwin any more.  That is the reason for the change larger than version.  Thanks for all you do!

**Pull request merged**
