### PR TITLE
Add support for the Instana self-hosted CLI

### PR DESCRIPTION
**Pull request by FrenchBen**
This adds an easier install path for those leveraging `krew` for plugin install - Docs: https://www.instana.com/docs/self_hosted_instana_k8s/instana_kubectl_plugin

### CODE REVIEW

**Comment by ahmetb** [comment]
@FrenchBen thanks for your submission.

It seems that Instana is an IBM project. Are you officially affiliated with it?

We expect the owners of the project to be involved with submission of their software on Krew so that they also can be onboard with updating versions here or installing hooks on their repo to automate releasing new versions.

**Comment by FrenchBen** [comment]
@ahmetb fair enough... I am not, but thought it would be a handy contribution 😅

**Comment by CodingFabian** [comment]
While we, Instana, consider this a great community contribution and addition to krew, we currently have no plans to support krew from our side.

**Comment by corneliusweig** [comment]
@CodingFabian Would you be ok, if someone sends PRs to setup [krew-release-bot](https://github.com/rajatjindal/krew-release-bot) for the instana tools? It automatically sends version bumps for the manifest when a new github release is pushed. For example https://github.com/corneliusweig/ketall/blob/370e67f95fb2d10ca9816a850baf892695e4c7a2/.github/workflows/ci.yml#L83-L87.

I think without having reliably the latest version in krew, this will not work out well.

**Comment by FrenchBen** [comment]
Closing, as it seems to not align with Instana practice.

**Pull request closed without merging**
