### PR TITLE
oke-cluster-start-stop new plugin

### PR DESCRIPTION
**Pull request by javiermugueta**
Plugin for start/stop all compute nodes of a k8s OKE (Oracle Kubernetes Engine) cluster
More info: https://github.com/javiermugueta/oke-cluster-start-stop

### CODE REVIEW

**Comment by ahmetb** [comment]
In the earlier thread you mentioned you work for OKE. 
In that case, can you host this repository somewhere more official instead of your personal repository?
Otherwise it would be problematic to distribute a tool that uses trademark that you do not own. 
Also, it’s always an option to release a monolithic plugin such as “oke-cluster” which can have start/stop subcommands. What do you think about these?

**Comment by corneliusweig** [comment]
Hey @javiermugueta, can you comment on the status of this plugin? Would it be possible to move this to an official git host as suggested by @.ahmetb?

**Comment by javiermugueta** [comment]
> In the earlier thread you mentioned you work for OKE.
> In that case, can you host this repository somewhere more official instead of your personal repository?
> Otherwise it would be problematic to distribute a tool that uses trademark that you do not own.
> Also, it’s always an option to release a monolithic plugin such as “oke-cluster” which can have start/stop subcommands. What do you think about these?

Hi, I work for Oracle but I not belong to OKE engineering team, I'm in touch with them to get support on how to get approvals for use the oke name, I have plans to start the approval today. Regarding moving the repo let me ask them and I'll come back with the answer.

Regarding start/stop subcommands is a good idea, I''l work on it.

**Comment by corneliusweig** [comment]
Thanks for that update. I'll put this PR on hold until those questions are resolved.
/hold

**Comment by ahmetb** [comment]
I think such plug-ins are better suited for a vendor controlled plugin index.

**Comment by javiermugueta** [comment]
Approval requested in case accepted project will be allocated at GitHub.com/oracle, will see

**Comment by corneliusweig** [comment]
Hey @javiermugueta , any news about moving the plugin repo into the oracle space?

**Pull request closed without merging**
