### PR TITLE
adding `kube-lock` plugin

### PR DESCRIPTION
**Pull request by ChaosInTheCRD**
Hi there 👋

I wish to add my kubectl tool` kube-lock as a krew plugin under the command `lock`. This allows people to easily lock and unlock Kubernetes contexts locally (all performed client side). I have tested it locally and all seems to work fine!

thanks,

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Hi, it's unclear from the description what locking is and what it does. It would be better if you can explain it more clearly.

**Comment by ChaosInTheCRD** [comment]
> Hi, it's unclear from the description what locking is and what it does. It would be better if you can explain it more clearly.

Hi Ahmet 👋 - I have updated the description. If it still isn't clear enough then please let me know. I am finding it a little tricky to give more detail within the character limits quoted below:

```
Eliminate redundant wording form shortDescription (it should be max 50 characters).
Try to word wrap your description to 80-character lines (no usage examples, please).
```

Ah man i've just realised it isn't an 80 character limit in the description, I misread 🤦‍♀️

**Comment by ChaosInTheCRD** [comment]
Hi 👋

I have updated the description accordingly, hopefully it meets the required standard @ahmetb ?

**Comment by ahmetb** [comment]
Would you consider a name like `lockctx` by any chance? `lock` is a pretty generic verb and assigning this to this plugin would prevent anyone else from claiming it for a potentially better use.

**Comment by ahmetb** [comment]
Also I noticed https://github.com/kubernetes-sigs/krew-index/blob/9449d397a524b1608588a824e97ca24800aafca1/plugins/safe.yaml this plugin is somewhat similar. Were you aware of it by any chance?

**Comment by ahmetb** [comment]
Sorry for the late review. 
/lgtm
/approve
Also, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

**Pull request merged**
