### PR TITLE
KUTTL 0.6.1 Bump

### PR DESCRIPTION
**Pull request by kensipe**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request seems to straightforward.
I'll go ahead and accept it. :+1: Cheers.

/lgtm
/approve

**Comment by kensipe** [comment]
interesting... I'll need to look into this

**Comment by corneliusweig** [comment]
@kensipe Have you found out why this PR failed or how to repair it? It would be great to resolve it one way or another.

**Comment by corneliusweig** [comment]
@kensipe ping. If this PR does not do the trick, let's close it maybe?

**Comment by ahmetb** [comment]
/close
feel free to make a new PR if you got a fix ready.

**Comment by kensipe** [comment]
lost track of this... thanks for the ping... I will look into it!

**Pull request closed without merging**
