### PR TITLE
Update MinIO to 4.1.3 release

### PR DESCRIPTION
**Pull request by nitisht**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/minio.yaml` is not a straightforward version bump: changing old version (`"4.1.2"`) with new version (`"4.1.3"`) in the url (`https://github.com/minio/operator/releases/download/v4.1.2/kubectl-minio_darwin_amd64.zip`) does not appear in the patch as `https://github.com/minio/operator/releases/download/v4.1.3/kubectl-minio_darwin_amd64.zip`

**Comment by ahmetb** [comment]
@nitisht there's a human mistake as noted above.
To avoid such errors, consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request seems to be a straightforward version bump. I'll go ahead and accept it. :+1: Cheers.

/lgtm
/approve

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request seems to be a straightforward version bump. I'll go ahead and accept it. :+1: Cheers.

/lgtm
/approve

**Comment by nitisht** [comment]
> @nitisht there's a human mistake as noted above by the bot (arm vs amd).
> 
> To avoid such errors, consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

Thanks @ahmetb , this looks great. We'll try to move to this soon.

**Pull request merged**
