### PR TITLE
rem dtlogin plugin

### PR DESCRIPTION
**Pull request by devopstales**

### CODE REVIEW

**Comment by ahmetb** [comment]
Are you moving to a custom index potentially or discontinuing the plugin altogether?

**Comment by devopstales** [comment]
I want to rename the plugin because I created a new server-side component for it. From dtlogin to kdlogin (KubeDash login).

**Comment by ahmetb** [comment]
Is this plugin not general purpose? Maybe you should look into distributing it in your custom index (easy to self-host).

**Comment by ahmetb** [comment]
I see you're already doing this in your repo. I will go ahead and accept this. 

/lgtm
/approve

**Pull request merged**
