### PR TITLE
KUDO 0.18.2 Bump

### PR DESCRIPTION
**Pull request by rishabh96b**
Signed-off-by: Rishabh Bohra <rishabhbohra01@gmail.com>
Resolves https://github.com/kubernetes-sigs/krew-index/issues/1033

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request seems to be a straightforward version bump. I'll go ahead and accept it. :+1: Cheers.

/lgtm
/approve

**Comment by ahmetb** [comment]
@rishabh96b 
If you are a contributor to KUDO, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

**Comment by rishabh96b** [comment]
Thanks @ahmetb ! I'll definitely look into this.

**Comment by ahmetb** [comment]
If you're not planning to sign the CLA, please close.

**Comment by corneliusweig** [comment]
@rishabh96b friendly ping. You need to sign the CLA or the bot won't merge the PR. Otherwise, please close.

**Comment by rishabh96b** [comment]
Thanks for the reminder @ahmetb and @corneliusweig . I am process to sign the CLA. Will provide the update on this soon.

**Comment by rishabh96b** [comment]
I signed it

**Comment by rishabh96b** [comment]
Looks like commenting "I signed it" (as mentioned [here](https://identity.linuxfoundation.org/projects/cncf)) did not retrigger the cla check.

**Pull request closed without merging**
