### PR TITLE
Add plugin: support-bundle

### PR DESCRIPTION
**Pull request by divolgin**
This is a new plugin that generates a support bundle for a cluster.

Example:

kubectl troubleshoot https://troubleshoot.replicated.com

The generated support bundle can be manually inspected or uploaded to https://vendor.replicated.com for automated analysis.

### CODE REVIEW

**Comment by ahmetb** [comment]
I think the name “troubleshoot” is far too generic per Krew’s naming guidelines. 
- It’s sort of a name grab (what happens when others want to develop troubleshooting plugins? what should they call them?)
- name doesn’t sufficiently describe what the plugin does (troubleshoot what? Nodes? Volumes? Load balancers? Perf issues?)

**Comment by divolgin** [comment]
I signed it

**Comment by divolgin** [comment]
@ahmetb I see how that name is generic.  The intention is to collect information that can be used for troubleshooting the entire cluster: nodes, volumes, load balancers, any applications that may be running on it, etc....  All this information is saved in a support bundle file.

I'll rename this to support-bundle.  That's does seem more specific about what this plugin does: generates a support bundle from a cluster.

**Comment by ahmetb** [comment]
Thanks, I think a name like `support-bundle` is definitely more appropriate and specific to make it clear that this is not as general-purpose as the original name reads.

**Comment by divolgin** [comment]
@ahmetb I've changed the name to `support-bundle`

**Comment by ahmetb** [comment]
Thanks.  I will accept the plugin but you have 3 visible issues:

1. the help message doesn't understand the new plugin name

```
kubectl support-bundle
Error: requires at least 1 arg(s), only received 0
Usage:
  troubleshoot [url] [flags]
  troubleshoot [command]
```

2. please consider adding `-n` flag in addition to namespace.

3. please consider importing auth plugins like `gcp`, `azure`, `oidc` etc in your code, otherwise this will not work with managed cloud clusters (e.g. GKE, AKS).

```
kubectl support-bundle https://troubleshoot.replicated.com
panic: No Auth Provider found for name "gcp"
```

**Pull request merged**
