### PR TITLE
feat: upgrade custom-cols plugin

### PR DESCRIPTION
**Pull request by fredleger**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this. If we don't respond within a day, feel free to ping us.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/custom-cols.yaml` is not a straightforward version bump: change on line `6` does not seem like a version bump: [`-  - selector:`]
/kind plugin-update

**Comment by fredleger** [comment]
Hello @ahmetb 
Unless i missed something, "krew-index CI / Validate plugin manifests (pull_request)" dind't run after branch update. Is this awaited ? How can i run checks again ? maybe closing the PR and reopen ?

**Comment by ahmetb** [comment]
It did run. There's an error with your version string.

**Comment by fredleger** [comment]
this seems like a bug / non wanted behavior to me
anyway i close the PR and open a new one

**Comment by fredleger** [comment]
reopen

**Pull request closed without merging**
