### PR TITLE
fix for homepage of viewnode

### PR DESCRIPTION
**Pull request by grafvonb**
Fix for the homepage of viewnode after updating the repo.

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/viewnode.yaml` is not a straightforward version bump: could not find the old/new version spec in the diff

**Comment by ahmetb** [comment]
let's sign the CLA
/lgtm
/approve
/hold

**Comment by grafvonb** [comment]
the CLA is signed

**Pull request merged**
