### PR TITLE
new version v0.2.0 of operator

### PR DESCRIPTION
**Pull request by joelanford**
Normal version bump, but this also adds platform support for darwin/arm64 for the `operator` plugin.

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/operator.yaml` is not a straightforward version bump: change on line `7` does not seem like a version bump: [`+    bin: kubectl-operator`]

**Comment by joelanford** [comment]
Seems like I need to wait for a new `krew` release that contains https://github.com/kubernetes-sigs/krew/pull/693 and then update the version of `validate-krew-manifest` used by the PR verifier in this repo, similar to #1041.

**Comment by ahmetb** [comment]
fixing this in #1043, but I'll manually merge this.
/lgtm
/approve

**Comment by joelanford** [comment]
Thanks for the fast turnaround on these PRs! In case you didn't have an M1 Mac laying around anywhere, I can confirm that krew v0.4.1 and this plugin installation worked no problem on mine.

**Pull request merged**
