### PR TITLE
IGNORE: auto-merge test #4

### PR DESCRIPTION
**Pull request by ahmetb**
-----PLEASE IGNORE----
Trying to see if bump PR auto-approver approves fast enough that can
possibly circumvent Travis CI run.
-----PLEASE IGNORE----

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request seems to be a straightforward version bump.
I'll go ahead and accept it. :+1: Cheers.

/lgtm
/approve

**Comment by ahmetb** [comment]
Well I guess I can't easily test this without creating a new account :P

**Comment by corneliusweig** [comment]
I'm quite confident that the robot will wait for the CI anyway. Otherwise, merges could also happen if somebody (manually) approves a PR before CI has finished.

**Comment by ahmetb** [comment]
> Otherwise, merges could also happen if somebody (manually) approves a PR before CI has finished.

yeah but as humans we're not as fast as Travis CI queueing a build and reporting back to github.

but this robot is faster than that.

Kubernetes CI check waits for Travis build to complete, but for that to happen, Travis needs to report an "in-progress" status back here indicating there's a build configured for this repo.

I'm nearly certain that if/when travis is down, Kubernetes CI bot will solely rely on lgtms from us (==bot now) and will merge directly.

Can you repeat this exact patch from your account please? Let's see if it happens.

**Pull request closed without merging**
