### PR TITLE
Add `epinio` plugin

### PR DESCRIPTION
**Pull request by enrichman**
Hi everyone :wave: 

I'm adding the [`kubectl-epinio`](https://github.com/enrichman/kubectl-epinio) plugin to help operators managing directly some [Epinio](https://epinio.io/) resources (https://github.com/epinio/epinio/).

Thank you!

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Is this not a standalone tool already? Why do you want to make it a kubectl plugin?

**Comment by enrichman** [comment]
@ahmetb yes but it's not the same. The `epinio` CLI is meant to be used by users without access to the cluster, without a Kubeconfig (they are calling the Epinio APIs).

This plugin can be used directly to interact with the Kube resources from the admins, managing resources where we don't have APIs yet, or when we don't want to give access to normal users.

Thanks for the legit question, the plugin was created during the SUSE HackWeek as a utility tool. 🙂

**Comment by ahmetb** [comment]
Since it's a project's name, we prefer the plugin comes from the project itself and not from a personal repo. The same rule applies to cloud vendors, brands etc.

**Comment by ahmetb** [comment]
/close

Please feel free to /reopen if you resolve the naming issues.

You can still distribute your plugin via Krew using custom indexes: https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes/ That way users can still install your plugin via Krew, but they'll be downloading the plugin manifest from your repository instead of krew-index.

**Pull request closed without merging**
