### PR TITLE
Add halloween plugin

### PR DESCRIPTION
**Pull request by scraly**
This plugin allows you to add randomly a Halloween emoji just before the resources name.
It's a special Halloween mode :-).

### CODE REVIEW

**Comment by ahmetb** [comment]
I think custom indexes are a better place to distribute this plugin. 

https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes/ That way users can still install your plugin via Krew, but they'll be downloading the plugin manifest from your repository instead of krew-index.

**Comment by corneliusweig** [comment]
Haha, this is funny :)

However, I agree that krew-index needs to keep its focus on plugins that increase productivity instead of scaring coworkers (^_^);
With custom indexes you can still easily install the plugin.

/close

**Comment by scraly** [comment]
Thanks for your feedbacks.
I know the plugin will be refused (at 99% ) ^^ but I've tried.
I will create my own index :).

FYI, this plugin have been created during the creation of a new talk about Kubernetes plugin creation and distribution through Krew :-)

**Comment by scraly** [comment]
Custom krew-index created: 

https://github.com/scraly/krew-index

Thanks :)

**Pull request closed without merging**
