### PR TITLE
release new version v0.5.0 of reliably

### PR DESCRIPTION
**Pull request by mperrien**
hey krew-index team,

I would like to open this PR to publish version v0.5.0 of Reliably.

Thanks,
Marc

Signed-off-by: Marc Perrien <marc@chaosiq.io>

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/reliably.yaml` is not a straightforward version bump: changing old version (`"0.3.0"`) with new version (`"0.5.0"`) in the url (`https://github.com/reliablyhq/cli/releases/download/v0.3.0/reliably_v0.3.0_darwin_amd64.tar.gz`) does not appear in the patch as `https://github.com/reliablyhq/cli/releases/download/v0.5.0/reliably_v0.5.0_darwin_amd64.tar.gz`

**Comment by mperrien** [comment]
Hello,

This wasn't submitted by krew-release-bot because of the issue mentioned a few days ago [1].

Also, it looks like it won't automatically merge because we changed our URLs. Sorry about that!

Marc

[1] https://github.com/kubernetes-sigs/krew-index/pull/1078

**Comment by ahmetb** [comment]
Your manifest isn't installing correctly. See error logs.

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/reliably.yaml` is not a straightforward version bump: changing old version (`"0.3.0"`) with new version (`"0.5.0"`) in the url (`https://github.com/reliablyhq/cli/releases/download/v0.3.0/reliably_v0.3.0_darwin_amd64.tar.gz`) does not appear in the patch as `https://github.com/reliablyhq/cli/releases/download/v0.5.0/reliably_v0.5.0_darwin_amd64.tar.gz`

**Comment by mperrien** [comment]
🤦‍♂️
Fixed...

**Pull request merged**
