### PR TITLE
feat(new-plugin): add new plugin network

### PR DESCRIPTION
**Pull request by wencaiwulue**
KubeVPN, A vpn tunnel tools which can connect to kubernetes cluster network, you can access remote kubernetes cluster network, remote kubernetes cluster service can also access your local service.

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
The name kubevpn goes against our naming guidelines. https://krew.sigs.k8s.io/docs/developer-guide/develop/naming-guide/

Also, does this tool enhance the kubectl experience or is it a standalone tool?

**Comment by wencaiwulue** [comment]
> The name kubevpn goes against our naming guidelines. https://krew.sigs.k8s.io/docs/developer-guide/develop/naming-guide/
> 
> Also, does this tool enhance the kubectl experience or is it a standalone tool?



> The name kubevpn goes against our naming guidelines. https://krew.sigs.k8s.io/docs/developer-guide/develop/naming-guide/
> 
> Also, does this tool enhance the kubectl experience or is it a standalone tool?

Ok, i will rename it meet requirement. It's a vpn tunnel tools which can connect to k8s cluster network, so it's a standalone tools, but it also can enhance the kubectl expericence

**Comment by wencaiwulue** [comment]
> The name kubevpn goes against our naming guidelines. https://krew.sigs.k8s.io/docs/developer-guide/develop/naming-guide/
> 
> Also, does this tool enhance the kubectl experience or is it a standalone tool?

Already rename, please have a look

**Comment by ahmetb** [comment]
There's usually a difference between standalone tools vs experiences enhancing kubectl experience of resource management etc by adding missing commands or providing alternatives to existing builtin commands. If you can make the case for it, I'd love to hear.

Historically we've rejected many standalone tools because they were Kubernetes related tools but not necessarily related to anything kubectl.

**Comment by ahmetb** [comment]
Also kube-vpn is not a good name either. Please refer to the naming guide. Similarly, a name like "vpn" won't be assigned as we get many plugin submissions with the same generic name with fairly different feature sets. So we try to prevent the firstcomer advantage.

**Comment by wencaiwulue** [comment]
> 

This tool can  enhance the kubectl experience, because it provide a function that connect to your k8s cluster network, you can access remote kubernetes resource in local, also can startup your application in local but using remote cluster midware, it also provide dns resolve, so if you are develop a k8s service, use kubectl tunnel can help you

**Comment by wencaiwulue** [comment]
> Also kube-vpn is not a good name either. Please refer to the naming guide. Similarly, a name like "vpn" won't be assigned as we get many plugin submissions with the same generic name with fairly different feature sets. So we try to prevent the firstcomer advantage.

Ok, i got it, so how about tunnel, `kubevpn tunnel` ?

**Comment by wencaiwulue** [comment]
This tool can  enhance the kubectl experience, because it provide a function that you can connect to your k8s cluster network, you can access remote kubernetes resource in local, also you can startup your application using remote cluster midware

> > 
> 
> This tool can enhance the kubectl experience, because it provide a function that connect to your k8s cluster network, you can access remote kubernetes resource in local, also can startup your application in local but using remote cluster midware, it also provide dns resolve, so if you are develop a k8s service, use kubectl tunnel can help you

and more, use this tool can proxy deployment traffic to local PC, so i think it can be enhance the kubectl experience

**Comment by ahmetb** [comment]
Sorry, the name `network` is also not going to work. It's very generic. Please refer to the naming guidelines I linked before.

Furthermore, the plugin directly installs components to the cluster without any prompt, and this is not obvious from help/description messages. This is problematical as people might run it on their sensitive clusters and unknowingly install something that they did not vet.

The plugin also does not enhance the resource management or the rest of kubectl experience; it does some bootstrapping and wiring to get you access to the cluster through various methods. These sort of tasks aren't great examples that should go into this curated repository and set example for future plugins that aren't a good fit.

I think the tool useful; it's just that it doesn't fit the bill to be a kubectl plugin, and may be better off as a standalone tool for now.

That said, you can still distribute your plugin via Krew using custom indexes: https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes/ That way users can still install your plugin via Krew, but they'll be downloading the plugin manifest from your repository instead of krew-index.

I'll close this for now.

/kind gray-area
/close

**Pull request closed without merging**
