### PR TITLE
add kbcli plugin

### PR DESCRIPTION
**Pull request by fengluodb**
- [kbcli](https://github.com/apecloud/kbcli) is A Command Line Interface for KubeBlocks
- [kubeblocks](https://github.com/apecloud/kubeblocks) is an open-source, cloud-native data infrastructure designed to help application developers and platform engineers manage database and analytical workloads on Kubernetes. It is cloud-neutral and supports multiple cloud service providers, offering a unified and declarative approach to increase productivity in DevOps practices.

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Hi, I am not able to infer from your readme how the tool looks like. Can you explain why you think this is a kubectl plugin that augments the kubectl experience as opposed to a standalone CLI tool.

**Comment by fengluodb** [comment]
> Hi, I am not able to infer from your readme how the tool looks like. Can you explain why you think this is a kubectl plugin that augments the kubectl experience as opposed to a standalone CLI tool.

We have update the readme of kbcli in https://github.com/apecloud/kbcli.

**Comment by ahmetb** [comment]
Thanks for pointing out. I am not sure if this plugin accompanies kubectl by enhancing the kubectl experience of managing Kubernetes resources. I recommend distributing this as a standalone tool.

**Comment by nashtsai** [comment]
> Thanks for pointing out. I am not sure if this plugin accompanies kubectl by enhancing the kubectl experience of managing Kubernetes resources. I recommend distributing this as a standalone tool.

Please take second look of current info, I believe it fall into same category as [MOCO Operator](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/moco.yaml)

**Pull request closed without merging**
