### PR TITLE
Adding edit-secret plugin

### PR DESCRIPTION
**Pull request by ljakimczuk**
-----
**Usage:**

```
Examples:
  # Edit Secret in the current namespace.
  kubectl secmod secret123

  # Edit Secret in the given namespace.
  kubectl secmod -n namespace123 secret123

Usage:
  kubectl secmod
[-n <NAMESPACE> | -h]
```

**Checklist for plugin developers:**

- [x] Read the [Plugin Naming Guide](https://sigs.k8s.io/krew/docs/NAMING_GUIDE.md) (for new plugins)
- [x] Verify the installation from URL or a local archive works (`kubectl krew install --manifest=[...] --archive=[...]`)

### CODE REVIEW

**Comment by ahmetb** [comment]
Looks like there’s a problem with the CLA. You may need to edit the commits bu rewriting and force pushing. 
Secmod isn’t a bad name fwiw, I like the creative and unique nature of it.

**Comment by ahmetb** [comment]
Pinging to see if you can fix the CLA issue.

**Comment by ljakimczuk** [comment]
@ahmetb sure, I'll deal with it this weekend, sorry for not doing this earlier, I was quite busy this week :/ Thank you for reviewing it and encouraging me to leave the `secmod` name, I changed it previously thinking it wouldn't fit the naming convention :)

**Comment by ahmetb** [comment]
/cc @corneliusweig 
as FYI for naming choice ^

**Comment by corneliusweig** [comment]
I would have preferred `edit-secret` because this plugin basically wants to fill the gap that secrets cannot be easily modified with `kubectl edit`. I think it would make the plugin more discoverable. But I'm fine with `secmod` too.

**Comment by ahmetb** [comment]
Yeah, `secmod` is unique, but also cryptic. `edit-secret` and `update-secret` are both better here IMO. But if the owner wants to go with `secmod` at their own risk of less discoverability, I'm ok with it.

**Comment by ahmetb** [comment]
@ljakimczuk  Can you sign the CLA?

**Comment by ahmetb** [comment]
/close
Due to inactivity.

**Pull request closed without merging**
