### PR TITLE
tree v0.3.0

### PR DESCRIPTION
**Pull request by volkancakil**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **doesn't** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/tree.yaml is not a straightforward version bump: changing old version ("0.2.0") with new version ("0.3.0") in the url (https://github.com/ahmetb/kubectl-tree/releases/download/v0.2.0/kubectl-tree_v0.2.0_darwin_amd64.tar.gz) did not result in the new url (https://github.com/ahmetb/kubectl-tree/releases/download/v0.2.0/kubectl-tree_v0.3.0_darwin_amd64.tar.gz), expected: https://github.com/ahmetb/kubectl-tree/releases/download/v0.3.0/kubectl-tree_v0.3.0_darwin_amd64.tar.gz

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **doesn't** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/tree.yaml is not a straightforward version bump: diff line unrecognized for version bumps: [+    selector:]

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **doesn't** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/tree.yaml is not a straightforward version bump: diff line unrecognized for version bumps: [+  - selector:]

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **doesn't** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/tree.yaml is not a straightforward version bump: diff line unrecognized for version bumps: [-  - selector:]

**Comment by ahmetb** [comment]
/lgtm
/approve
/hold
Do you know why the extra indentation was added under platforms: field?
If we can undo that, future PRs might merge automatically as they would be pure version bumps.

**Comment by ahmetb** [comment]
Closing in favor of automated version in #414.

**Comment by volkancakil** [comment]
@ahmetb thank you for this handy tool.

**Pull request closed without merging**
