### PR TITLE
adding new plugin 'context'

### PR DESCRIPTION
**Pull request by stefanm8**

### CODE REVIEW

**Comment by stefanm8** [comment]
I signed the CLA

**Comment by ahmetb** [comment]
Thanks for submitting this plugin. Since we already have a plugin called ctx that does nearly the same functionality, it’s very likely we’ll turn this down. Can you please compare the two?

**Comment by stefanm8** [comment]
Thanks for looking over it.

The main difference is that it matches a substring in the name of the context and displays the information as kubectl config get-contexts does, it just applies color to the current context.

**Comment by corneliusweig** [comment]
The `ctx` plugin already highlights the current context and it allows to select a context by fuzzy matching via fzf. So your plugin does not really add anything that's not already there. Or did I miss something?

There is precedent that we turn down plugins that are too similar to other plugins that are already in the index (https://github.com/kubernetes-sigs/krew-index/pull/429, https://github.com/kubernetes-sigs/krew-index/pull/351). Especially in the realm of switching context, there is no added value of having several similar alternatives in the index.
My recommendation: if you find that `ctx` is missing something, open an issue there and submit a PR if you get good feedback.

**Comment by ahmetb** [comment]
> The main difference is that it matches a substring in the name of the context and displays the information as kubectl config get-contexts does, it just applies color to the current context.

ctx plugin supports all of those when fzf is installed.

**Comment by stefanm8** [comment]
Fair enough, I was not familiar with fzf, doesn't look like it can match a substring but a prompt serves pretty well. 

Thanks for commentaries

**Pull request closed without merging**
