### PR TITLE
Update kube-capacity to v0.6.0

### PR DESCRIPTION
**Pull request by chunliu**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/resource-capacity.yaml` is not a straightforward version bump: changing old version (`"0.4.0"`) with new version (`"0.6.0"`) in the url (`https://github.com/robscott/kube-capacity/releases/download/0.4.0/kube-capacity_0.4.0_Darwin_x86_64.tar.gz`) does not appear in the patch as `https://github.com/robscott/kube-capacity/releases/download/0.6.0/kube-capacity_0.6.0_Darwin_x86_64.tar.gz`

**Comment by corneliusweig** [comment]
@chunliu Please sign the CLA, so that I can merge your PR.

**Comment by chunliu** [comment]
@corneliusweig done. thx.

**Pull request merged**
