### PR TITLE
Bump preflight to 0.9.2

### PR DESCRIPTION
**Pull request by divolgin**

### CODE REVIEW

**Comment by divolgin** [comment]
I signed it

**Comment by divolgin** [comment]
I signed it

**Comment by divolgin** [comment]
I signed it

**Comment by ahmetb** [comment]
The CLA signing doesn’t seem to have worked. Can you try again following the instructions?

**Comment by divolgin** [comment]
I signed it

**Comment by divolgin** [comment]
@ahmetb got signing sorted.  Thanks.

**Pull request merged**
