### PR TITLE
Kubectl-use plugin

### PR DESCRIPTION
**Pull request by kvaps**
Tiny plugin for easy switch between Kubernetes contexts and namespaces

### CODE REVIEW

**Comment by ahmetb** [comment]
This sounds a lot like `ctx`, `ns` and `change-ns` plugins that we already have. :) Due to their existing user base and popularity, I'm inclined to not having this in the centralized index, also due to the vague name "use" which goes against our naming recommendations.

**Comment by corneliusweig** [comment]
I also think that it does not make sense to have this particular plugin in the index. As already said, there already are `ctx` and `ns` which are pretty widespread and also offer a nice interactive switcher.
Or where do you see a unique feature of `use` that the other options do not offer?

**Comment by corneliusweig** [comment]
Hearing no unique selling points for this plugin over `ctx`/`ns`, let's stick with what we already have in krew-index. Thanks for submitting anyway!

/close

**Pull request closed without merging**
