### PR TITLE
updates fleet plugin

### PR DESCRIPTION
**Pull request by mhausenblas**
Signed-off-by: Michael Hausenblas <hausenbl@amazon.com>

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **doesn't** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/fleet.yaml is not a straightforward version bump: diff line unrecognized for version bumps: [+    files:]

**Comment by ahmetb** [comment]
/lgtm
/approve 
Thanks.

**Comment by ahmetb** [comment]
Looks like CI is failing because we don’t support arm64 for krew yet. Do you mind commenting out that or taking it off altogether?

**Comment by mhausenblas** [comment]
@ahmetb well that is very sad (the lack of support for `arm64`) since that was one of the main motivations behind this release ;)

What can I do to help make this change?

**Comment by ahmetb** [comment]
Right now there aren’t many krew users on that platform so we have not heard demand. 

Since krew isn’t installable there, the plugin won’t be either. Is it very sad indeed or can those users unblock themselves by downloading the binary themselves? (Our main value add “upgrades” are for desktop operating systems which likely aren’t arm64.)

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **doesn't** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/fleet.yaml is not a straightforward version bump: diff line unrecognized for version bumps: [-      or https://github.com/mhausenblas/kcf/blob/v0.1.3/doc/USAGE.md]

**Comment by mhausenblas** [comment]
@ahmetb removed it (for now) but still very interested to fix the Arm situation. For the record, I did successfully install `krew` on Arm (my Kube RPI cluster) so not 100% sure I'm following. Maybe we should have the convo in a separate issue?

**Comment by ahmetb** [comment]
Hmm I forgot we have a linux/arm distribution for krew. My bad. 
I suspect arm64 != arm, that’s why it might not be working?

We support linux/arm for plugins (e.g. krew itself is a plugin) https://github.com/kubernetes-sigs/krew/blob/66348909fe8dd5dab480d353ff625d1d8f696b85/cmd/validate-krew-manifest/main.go#L198

However I am not sure why arm64 is not working. Is that a different GOARCH value? How is it different than arm? Do most/all arm executables work on arm64? I am not experienced enough in this field.

**Comment by ahmetb** [comment]
Yeah lets do a separate issue on “krew” repo. Thank you. 🙏. 
/lgtm
/approve

**Pull request merged**
