### PR TITLE
`kubectl explore` plugin

### PR DESCRIPTION
**Pull request by kei6u**
This patch introduces `kubectl explore` as a kubectl plugin.

**Local installation**

Screen Shot 2022-01-06 at 22 55 34

**Plugin help**

Screen Shot 2022-01-06 at 22 57 25

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
/lgtm
@corneliusweig or @chriskim06 to approve.

**Comment by kei6u** [comment]
@corneliusweig @chriskim06 Could you review it please?

**Comment by ahmetb** [comment]
/approve
I've tried it and seems to be working ok.

**Pull request merged**
