### PR TITLE
Fix file ending of tail manifest

### PR DESCRIPTION
**Pull request by corneliusweig**
`krew search` currently errors with 
```
E0530 00:15:40.510669    5529 scanner.go:57] failed to load file "tail", err: open ~/.krew/index/plugins/tail.yaml: no such file or directory
```

-----

**Checklist for plugin developers:**

- [x] Read the [Plugin Naming Guide](https://github.com/GoogleContainerTools/krew/tree/master/docs/NAMING_GUIDE.md) (for new plugins)
- [x] Verify the installation from URL or a local archive works (`kubectl krew install --manifest=[...] --archive=[...]`)

### CODE REVIEW

**Comment by corneliusweig** [comment]
Btw, I think there should be a test that checks if all plugins have the correct ending.

**Comment by corneliusweig** [comment]
@ahmetb There was a typo with `/lgtm`.

**Comment by ahmetb** [comment]
Oops

/lgtm

**Pull request merged**
