### PR TITLE
Update ingress-nginx plugin

### PR DESCRIPTION
**Pull request by aledbf**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/ingress-nginx.yaml is not a straightforward version bump: changing old version ("0.25.0") with new version ("0.31.0") in the url (https://github.com/kubernetes/ingress-nginx/releases/download/nginx-0.25.0/kubectl-ingress_nginx-darwin-amd64.tar.gz) does not appear in the patch as https://github.com/kubernetes/ingress-nginx/releases/download/nginx-0.31.0/kubectl-ingress_nginx-darwin-amd64.tar.gz

**Comment by rajatjindal** [comment]
Hi @aledbf 

wondering if you will be interested (and it will be acceptable in the org) to start using [krew-release-bot](https://github.com/rajatjindal/krew-release-bot) for updating new versions of ingress nginx automatically.

it does NOT need any credentials/access (for public repos) for automating doing this PR business.

**Comment by aledbf** [comment]
@rajatjindal thank you for the info. Right now the update is manual due to the restricted permissions and the things we need to run. I'll try to add the bot in the release.

**Pull request merged**
