### PR TITLE
new gke-policy plugin

### PR DESCRIPTION
**Pull request by mikouaj**
Added new plugin for [GKE Policy Automation](https://github.com/google/gke-policy-automation) tool.

### CODE REVIEW

**Comment by ahmetb** [comment]
Hi, are you submitting this at an official capacity and will the company maintain submitting version updates to Krew?

**Comment by mikouaj** [comment]
Hi @ahmetb, yes the version updates will be submitted to Krew by the `rajatjindal/krew-release-bot` during the tool's release workflow. I just can't proceed with Easy CLA as it claims that Google has no CLA signed, which is quite strange.

**Comment by mikouaj** [comment]
Hi @ahmetb this one is ready to be reviewed once you are free, thanks!

**Comment by ahmetb** [comment]
/lgtm
/approve
Thanks!

Also, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

**Pull request merged**
