### PR TITLE
new version v1.1.2 of node-shell

### PR DESCRIPTION
**Pull request by kvaps**
ref https://github.com/kvaps/kubectl-node-shell/pull/11

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **doesn't** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/node-shell.yaml is not a straightforward version bump: could not find the old/new version spec in the diff

**Comment by ahmetb** [comment]
You need to also update version field. Consider reading release automation from our docs.

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request seems to be a straightforward version bump.
I'll go ahead and accept it. :+1: Cheers.

/lgtm
/approve

**Comment by kvaps** [comment]
sure, my bad

**Pull request merged**
