### PR TITLE
bump kubetap v0.1.2

### PR DESCRIPTION
**Pull request by Eriner**
Bump kubetap version to v0.1.2

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/tap.yaml is not a straightforward version bump: changing old version ("0.1.1") with new version ("0.1.2") in the url (https://github.com/soluble-ai/kubetap/releases/download/v0.1.1/kubetap_0.1.1_Windows_x86_64.zip  ) does not appear in the patch as https://github.com/soluble-ai/kubetap/releases/download/v0.1.2/kubetap_0.1.2_Windows_x86_64.zip

**Comment by Eriner** [comment]
I've added the krew-release-bot to the CI pipeline in https://github.com/soluble-ai/kubetap/commit/8bfe14c52a1bf7730b2b74d3909933ae0cb337d0#diff-66f240bb15f0af2b64b165981f9ebe72R1, so this process should be automated in the future. Cheers!

**Pull request merged**
