### PR TITLE
new plugin: std-json

### PR DESCRIPTION
**Pull request by fleeto**
Export Kubernetes object in JSON format with a clean and sorted style. Remove some auto-generated fields and then sort fields in it.

### CODE REVIEW

**Comment by ahmetb** [comment]
Hi, thanks for your submission. This seems quite overlapping with existing `-o=json` flag for kubectl get + [eksporter](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/eksporter.yaml) plugin which we already have. When we run into this situation, we look for significant differentiation before accepting very similar plugins.

**Comment by corneliusweig** [comment]
There are even two plugins in that niche: https://github.com/itaysk/kubectl-neat

Please let us know how your plugin is different.

**Comment by fleeto** [comment]
neat
The first one is neat, and the second one is eksporter. 

But you are right, there is no significant difference, it's just simple and correct, just for me.

**Pull request closed without merging**
