### PR TITLE
Update ingress-nginx from 0.24.0 to 0.25.0

### PR DESCRIPTION
**Pull request by JJJJJones**
Hello, this is a simple bump to July 8th's plugin release of ingress-nginx

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request seems to be a straightforward version bump.
I'll go ahead and accept it. :+1: Cheers.

/lgtm
/approve

**Comment by ahmetb** [comment]
Please sign the CLA.

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request seems to be a straightforward version bump.
I'll go ahead and accept it. :+1: Cheers.

/lgtm
/approve

**Comment by JJJJJones** [comment]
> [APPROVALNOTIFIER] This PR is **APPROVED**
> 
> This pull-request has been approved by: _[ahmetb](https://github.com/kubernetes-sigs/krew-index/pull/268#issuecomment-540824781)_, _[JJJJJones](https://github.com/kubernetes-sigs/krew-index/pull/268#)_
> 
> The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=kubernetes-sigs%2Fkrew-index).
> 
> The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)
> Needs approval from an approver in each of these files:

/check-cla

**Pull request closed without merging**
