### PR TITLE
Add diag plugin

### PR DESCRIPTION
**Pull request by yuval-k**
A plugin to help diagnose problems I encountered when debugging istio.

The main feature is that it allows redirecting traffic from a pod to a laptop (which I use to get envoy to talk with my pilot running on my laptop). There are other tools as well (multi pod log output, and debug shell)

I named this `diag` so it is short to type, but I'm open to suggestions here.
If this will be accepted I will add release automation.

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
I think an alternative name would be better than assigning `diag` to a plugin only related to Istio. `istio-diag` is appropriate however.

**Comment by yuval-k** [comment]
> I think an alternative name would be better than assigning `diag` to a plugin only related to Istio. `istio-diag` is appropriate however.

while the examples are istio focused, I use this to debug also other client/server systems, where i want to debug how the server responds to a specific client. (i didn't have examples for these as they are internal systems). there is nothing istio specific in the plugin itself.

I plan to add another tool that lets you start a shell in distroless/"scratch" containers.

Perhaps `srv-diag` (i.e. server diagnostics) ?

**Comment by ahmetb** [comment]
I think I see the usefulness, but I am also trying to understand how does this relate to ephemeral containers (and also the builtin `kubectl debug` command). Can you elaborate further?
At any rate I think the shortDescription/description should be clear enough that users don't find themselves asking these questions.

**Comment by yuval-k** [comment]
make a lot of sense! thanks for the feedback.

Ephemeral containers are used to attach a container to a running pod. That container has a component that helps sets up the traffic redirection. specifically this means setting up iptables rules, and proxying connections.

The reason i use ephemeral container and not just exec to the pod is two fold: 1. i can ask an ephemeral container with the capabilities i need and 2. i have all the tools needed (i.e. iptables binary).

I also plan to  add to the ephemeral container a static variant of standlone ash (the busybox shell), and a tool to start in the pod's namespaces, so that you can have a usable shell in scratch containers.

**Comment by ahmetb** [comment]
OK, got it. So you're using ephemeral containers and changing some things in the net ns etc to route traffic.
I'm giving this feedback mostly because your plugin seems to be new:

My observation is that you have 2 sub-commands:
- redir: makes perfect sense, unique functionality. should be a plugin.
- shell: seems to be duplicating functionality with the builtin `kubectl debug --image=` cmd which also uses ephemeral containers. If that is the case, I recommend not doing that (unless you provide an obvious differentiator)

So I recommend instead of trying to build a Swiss army knife, try to build more focused tools. The lack of focus is clear from the current `shortDescription: Diagnostics tools for kubernetes developers.`. (As a user, I can't tell what you're diagnosing from this description. It can be dozens of different things.)

So I'd love to have you think about whether you really want to turn this into a Swiss army knife and use name `diag` which will impede your discoverability OR scope down to `redir` and get that plugin name.

**Comment by yuval-k** [comment]
The main differentiator i plan to add is that the shell will work for scratch containers. I.e. it will feel like  `kubectl shell pod` will behave like `kubectl exec -ti pod -- /bin/bash` but will work even if the pod doesn't have bash (using ephemeral containers and `execveat`).

If I'll complete that feature first would you be ok having both in the plugin? or would you still prefer separate ones? 
if you still prefer separate ones, I'll restructure the code so that `redir` is an independent krew plugin (while keeping the rest of the functionality in a separate binary not published in krew-index).

**Comment by ahmetb** [comment]
> The main differentiator i plan to add is that the shell will work for scratch containers. I.e. `kubectl shell pod` will behave like `kubectl exec -ti pod -- /bin/bash` but will work even if the pod doesn't have bash (using ephemeral containers and `execveat`).

I am still not understanding how is it different than "kubectl debug" because `kubectl debug --image=bash` does what you described to a scratch container?



> If I'll complete that feature first would you be ok having both in the plugin? or would you still prefer separate ones?

I am actually ok with the name diag as it's specific enough that others won't come asking for the same name. I'm more worried about your plugin's discoverability among the catalog of ~200 plugins. Neither the name nor the description clearly explains what the plugin does.

**Comment by yuval-k** [comment]
Hi @ahmetb , finally had some time this weekend and I updated the repo and the description.
Hopefully it's more clear now - let me know what you think!

The common thread of the tools in this package is that I found them useful when debugging istio.

**Pull request closed without merging**
