### PR TITLE
Add kubectl-moco plugin to krew index

### PR DESCRIPTION
**Pull request by d-kuro**
Add the kubectl-moco plugin to the krew index.

MOCO is a MySQL operator on Kubernetes.
Read more documentation at: https://cybozu-go.github.io/moco/index.html

### CODE REVIEW

**Comment by d-kuro** [comment]
I have a Pull Request that was wrong created by a bot.
I'm sorry, but please close the wrong Pull Request 🙏 
https://github.com/kubernetes-sigs/krew-index/pull/1716

**Review by ahmetb — CHANGES_REQUESTED** [review]
Please delete until Control*

See other plugin descriptions and how they fit to screen around 55 chars in krew list output.

**Comment by d-kuro** [comment]
@ahmetb 

> See other plugin descriptions and how they fit to screen around 55 chars in krew list output.

I see. Thank you comments.
I fixed the short description.
https://github.com/kubernetes-sigs/krew-index/pull/1721/commits/97de5b14825aa6ba698eaa593afb6ddb836d2917

**Comment by ahmetb** [comment]
Apologies for the delay here @d-kuro.
/lgtm
/approve

**Pull request merged**
