### PR TITLE
chore: update kubesec-scan to v1.1.0, add new arch

### PR DESCRIPTION
**Pull request by spiarh**
Signed-off-by: spiarh <controlplane@spiarh.fr>

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this. If we don't respond within a day, feel free to ping us.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/kubesec-scan.yaml` is not a straightforward version bump: change on line `7` does not seem like a version bump: [`+    files:`]
/kind plugin-update

**Comment by spiarh** [comment]
I'm waiting on our CLA manager who is currently in an other timezone. Keep this in draft for now.

**Comment by spiarh** [comment]
Apologize for the delay, this is ready now. Thanks.

**Comment by spiarh** [comment]
Any chance to get a look to this PR from someone ? Thanks!

**Comment by ahmetb** [comment]
Apologies it slipped though. 
/lgtm
/approve

**Pull request merged**
