### PR TITLE
add cache plugin

### PR DESCRIPTION
**Pull request by yhlooo**
add cache plugin

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Hi, thanks for submission. Per naming guidelines, we usually try not to grant very broad terms to plugins to prevent the firstcomer advantage. Do you have any alternative names in mind?

**Comment by yhlooo** [comment]
> Hi, thanks for submission. Per naming guidelines, we usually try not to grant very broad terms to plugins to prevent the firstcomer advantage. Do you have any alternative names in mind?

Thank you for reviewing my PR promptly.

I have reviewed the [Plugin Naming Guide](https://krew.sigs.k8s.io/docs/developer-guide/develop/naming-guide/). The name `cache` is indeed quite broad, but the functionality of this plugin is also quite broad. Essentially, it works similarly to `kubectl get` and `kubectl proxy`, **but with cache**. I believe that prefixing these commands with `cache` is intuitive.

Moreover, I have noticed that there are many other broadly named plugins in the krew-index, such as `ctx`, `lock`, `cost`, `count`, `http`, etc. Therefore, I think that even though `cache` is broad, as long as it is easily understood, it should be acceptable.

Before starting this project, I searched both GitHub and the krew-index and found no similar tools or names, which means there should be no confusion.

If `cache` is not acceptable, my second suggestion is `kubectl with-cache ...`. This name is a bit longer and still quite broad.

**Comment by ahmetb** [comment]
That’s reasonable, thanks.

**Comment by ahmetb** [comment]
/lgtm
/approve
Also, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

**Pull request merged**
