### PR TITLE
Update example.yaml

### PR DESCRIPTION
**Pull request by seredot**
Example plugin add missing architectures and M1 support for Mac.

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this. If we don't respond within a day, feel free to ping us.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/example.yaml` is not a straightforward version bump: change on line `10` does not seem like a version bump: [`+    - selector:`]
/kind plugin-update

**Comment by seredot** [comment]
@ahmetb Is this platform really invalid? Arm on Windows?

```
spec.platform[6]'s selector (&LabelSelector{MatchLabels:map[string]string{arch: arm,os: windows,},MatchExpressions:[]LabelSelectorRequirement{},}) doesn't match any supported platforms
```

**Comment by ahmetb** [comment]
@seredot sorry for the delay. Please refer to the Krew's own binary releases to see which platforms are supported. 

(If user can't install krew, then they can't install your plugin either).

**Pull request merged**
