### PR TITLE
Add dumpy plugin v0.1.0

### PR DESCRIPTION
**Pull request by larryTheSlap**
This plugin make capturing network traffic easy on containers for different kubernetes resources (deployments, replicasets, pods...).
More details on : https://github.com/larryTheSlap/dumpy

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Do you mind explaining if this is a subset of `sniff` plugin that already exists? https://github.com/kubernetes-sigs/krew-index/blob/9449d397a524b1608588a824e97ca24800aafca1/plugins/sniff.yaml#L15

**Comment by larryTheSlap** [comment]
I would not consider dumpy as a subset of ksniff but a different way to capture network traffic in Kubernetes, also ksniff is no longer maintained.

**Comment by larryTheSlap** [comment]
Hello @ahmetb, may i have some news about this PR please ?

**Comment by ahmetb** [comment]
/lgtm
/approve
Thanks!

Also, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

**Pull request merged**
