### PR TITLE
Update virt (KubeVirt virtctl plugin package) to v0.27.0

### PR DESCRIPTION
**Pull request by dhiller**
See https://github.com/kubevirt/kubevirt/releases/tag/v0.27.0

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **doesn't** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/virt.yaml is not a straightforward version bump: could not find the old/new version spec in the diff

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **doesn't** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/virt.yaml is not a straightforward version bump: could not find the old/new version spec in the diff

**Comment by dhiller** [comment]
The original PR had issues with a broken package that didn't get caught by installer check (empty binary file). This one corrects this by pointing at new packages.

**Comment by ahmetb** [comment]
/lgtm
/approve
Thanks!

**Pull request merged**
