### PR TITLE
Add resource-report to index

### PR DESCRIPTION
**Pull request by NoUseFreak**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Hi, do you mind explaining the difference between this plugin and resource-snapshot (or similar resource/allocation plugins)?

**Comment by NoUseFreak** [comment]
Hi,

Collation can be done during a defined duration.
Suggestions about resources are indicated in color. (more to follow)

**Comment by ahmetb** [comment]
Just tried it and it seems it's unique in a way that it shows low/high utilizations and gets active usage from metrics server, which makes it differentiating. Looks like the build is failing.

**Pull request closed without merging**
