### PR TITLE
update minio.yaml v5.0.2

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this. If we don't respond within a day, feel free to ping us.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/minio.yaml` is not a straightforward version bump: change on line `3` does not seem like a version bump: [`-    - selector:`]
/kind plugin-update

**Comment by ahmetb** [comment]
May I ask what tool are you using to generate manifests that's not respecting a consistent order? It will continue adding latency to get your PRs merged if it doesn't follow the previous ordering.

**Comment by ahmetb** [comment]
Ping @Harshavardhana.

**Comment by harshavardhana** [comment]
> May I ask what tool are you using to generate manifests that's not respecting a consistent order? It will continue adding latency to get your PRs merged if it doesn't follow the previous ordering.

This was a mistake due to some Python code that had the wrong spaces apparently, 
and the previous submitter manually fixed the indentation to satisfy YAML.

```
selector:
- value
```

to
```
selector:
  - value
```

Both are valid in YAML.

**Comment by ahmetb** [comment]
Understood. Thanks. 
/lgtm
/approve

**Pull request merged**
