### PR TITLE
Add `save` plugin

### PR DESCRIPTION
**Pull request by nathforge**

### CODE REVIEW

**Comment by nathforge** [comment]
CLA is now signed...

**Comment by ahmetb** [comment]
Thanks. This name will not work. Did you have a chance to read the naming style guide?

Please read this comment as it exactly applies here: https://github.com/kubernetes-sigs/krew-index/pull/687#issuecomment-655077038

**Comment by nathforge** [comment]
Thanks for the quick feedback @ahmetb - would `split-yaml` be better?

**Comment by ahmetb** [comment]
Yeah we can think about the name a bit. “To-files” isn’t a bad name either. Or “dump-files”, “takeout”, “yaml2files”, or some more unique and creative name you can think of.

**Pull request closed without merging**
