### PR TITLE
Migrate mtail to new repo and bump version to 1.1.0

### PR DESCRIPTION
**Pull request by grzesuav**
Moved to new repository and added new features, please check
https://gitlab.com/grzesuav/kubectl-mtail/-/releases for details.

Verified locally

### CODE REVIEW

**Comment by grzesuav** [comment]
Signed CLA

**Comment by corneliusweig** [comment]
So it seems you had an agreement to move `mtail` out of kubectl-extras to its own repository? I found this: https://github.com/ahmetb/kubectl-extras/pull/7#issuecomment-504292816

@ahmetb Do you still want to hand over control of this plugin?

@grzesuav Are you sure with your decision to host on gitlab instead of github? Using a different platform than github will reduce the plugin discoverability.

Apart from those questions, everything looks fine and dandy.

**Comment by grzesuav** [comment]
> So it seems you had an agreement to move `mtail` out of kubectl-extras to its own repository? I found this: [ahmetb/kubectl-extras#7 (comment)](https://github.com/ahmetb/kubectl-extras/pull/7#issuecomment-504292816)
> @grzesuav Are you sure with your decision to host on gitlab instead of github? Using a different platform than github will reduce the plugin discoverability.
> 
Hi, I choose gitlab as it provides more complex solution (CI integration). I am not sure if I understand correctly argument with discoverability, you have in mind that it won't be present in github search and tags ?

**Comment by ahmetb** [comment]
We don't enforce GitHub over GitLab.

In the future we might build tools (such as a tool to automatically pick up new releases and update manifests) and those would work only for GitHub (unless someone is willing to contribute GitLab change).

Right now 100% of the plugins we have are hosted on GitHub which makes it much easier to build such tooling but we definitely don't restrict as for where the source code resides.

**Comment by ahmetb** [comment]
> @ahmetb Do you still want to hand over control of this plugin?

Yeah I am hoping @grzesuav can rewrite it in Go or something.

**Comment by corneliusweig** [comment]
Should we feel the need to host all plugins on GitHub we can do a second repo migration in the future.

/retitle Migrate mtail to new repo and bump version to 1.1.0
/lgtm

**Comment by grzesuav** [comment]
@ahmetb about automatic updates, as I mentioned in https://github.com/eldadru/ksniff/issues/32 , it should be possible to extend renovate to cover this case

**Comment by ahmetb** [comment]
@grzesuav we're planning to create a tool to bump up plugin versions automatically  or manually (join the discussion at https://github.com/kubernetes-sigs/krew/issues/239)

**Pull request merged**
