### PR TITLE
New version v1.3.0 of kyverno

### PR DESCRIPTION
**Pull request by realshuting**
Signed-off-by: Shuting Zhao <shutting06@gmail.com>

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request seems to straightforward.
I'll go ahead and accept it. :+1: Cheers.

/lgtm
/approve

**Comment by realshuting** [comment]
Hi @ahmetb, any idea why the test is failing? Is there something I need to change on my side?

**Comment by ahmetb** [comment]
> tee: /dev/stderr: No such device or address

That's a weird error that doesn't have anything to do with us. 😇 I'll re-run to see if it fixes.

**Comment by realshuting** [comment]
Seems it failed again, it could be related to this configuration https://github.com/kubernetes-sigs/krew-index/blob/8c15c58e1975da7e3166a4a854426813b4bcf34f/.github/workflows/ci.yml#L54

Found a similar issue that may help https://unix.stackexchange.com/questions/401372/dev-stderr-in-systemd-service.

**Comment by ahmetb** [comment]
I honestly don't know how to fix that error.
The workaround in the linked question is definitely something we wouldn't try to incorporate. It could be something recently changed with GitHub Actions. We probably need to investifate.
If you can locally validate using that script, I'm happy to merge.

**Comment by realshuting** [comment]
I'm happy to give it a try! 

Before I do that, is there a way to submit another PR using krew-release-bot? The previous one configured in our GitHub Action was broken.

**Comment by ahmetb** [comment]
I'll manually merge this if you can verify locally.
Since this happened only once out of ~1000 PRs, I'm inclined to think it might be a one-off.

**Comment by realshuting** [comment]
Sure, thanks!

**Comment by realshuting** [comment]
I guess I'm a bit confused here - do you want me to verify the installation after you merge the PR or what do I need to verify?

**Comment by realshuting** [comment]
@ahmetb Does this look good?
```
 ✗ validate-krew-manifest -manifest ./plugins/kyverno.yaml
I0120 15:56:34.635689   69446 main.go:67] reading file "./plugins/kyverno.yaml"
I0120 15:56:34.638047   69446 main.go:84] structural validation OK
I0120 15:56:34.638230   69446 main.go:92] all spec.platform[] items are used
I0120 15:56:34.638461   69446 main.go:98] no overlapping spec.platform[].selector
I0120 15:56:34.638473   69446 main.go:102] installing spec.platform[0]
I0120 15:56:38.579827   69446 main.go:106] installed  spec.platforms[0]
I0120 15:56:38.579861   69446 main.go:102] installing spec.platform[1]
I0120 15:56:44.755277   69446 main.go:106] installed  spec.platforms[1]
I0120 15:56:44.755306   69446 main.go:102] installing spec.platform[2]
I0120 15:56:51.045589   69446 main.go:106] installed  spec.platforms[2]
2021/01/20 15:56:51 all 3 spec.platforms installed fine
````

**Pull request merged**
