### PR TITLE
Add approve-csrs plugin

### PR DESCRIPTION
**Pull request by RyanMillerC**
Add approve-csrs plugin to index https://github.com/RyanMillerC/oc-approve-csrs

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Typically we don't accept one liners here as plugins as they don't provide nontrivial functionality, become a maintenance burden, go out of date and eventually break (rarely happens to oneliners around kubectl). If I am missing some substantial functionality please let me know. 
/kind gray-area

**Comment by RyanMillerC** [comment]
It's basically a one-liner. If it finds any pending certs it will wait 10 seconds and look for more certs. I need to do this a few times a month so I made a plugin for it.

Anyone can install it using krew by specifying a manifest-url that points to my repo so it's not a huge deal if it's not accepted here:

```bash
$ oc krew install --manifest-url=https://raw.githubusercontent.com/RyanMillerC/oc-approve-csrs/main/krew-plugin.yaml
```

**Comment by ahmetb** [comment]
You can still distribute your plugin via Krew using custom indexes: https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes/ That way users can still install your plugin via Krew without specifying a manifest URL —they'll be downloading the plugin manifest from your repository instead of krew-index. That way, they can get version upgrades of your plugin along with other plugins upgrades.

**Comment by ahmetb** [comment]
Let's distribute this on your own repository for now. Thanks for the submission here.
/close

**Pull request closed without merging**
