### PR TITLE
Add clean plugin

### PR DESCRIPTION
**Pull request by shardulsrivastava**
Add clean plugin.

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
The name is too generic. Please refer to naming guidelines.

**Comment by ahmetb** [comment]
We also have the rm-standalone-pods plugin, please quantify (as a comment as well as in your plugin description field) what orphaned means.

**Comment by shardulsrivastava** [comment]
@ahmetb thanks for your review, I will change the plugin name to be specific. This plugin is different from `m-standalone-pods` that you are mentioning.  If you're using `Spot instances` in EKS or `Pre-emptible instances` in GKE, when those instances go away, there will be a lot of pods (or just their reference) left, resulting in pods in `Evicted/NodeShutdown/Terminated` states or orphaned pods from jobs in `Completed`. This plugin helps to clean them all up.

**Comment by ahmetb** [comment]
I am not sure if that makes a lot of sense based on what you said. That sounds like the job of the respective workload controller to clean up a Job pod that's completed or a Pod whose Node went away. 

I don't know what this would be a manual task. Are you positive on how k8s workload controllers are supposed to work in this regard?

**Comment by shardulsrivastava** [comment]
@ahmetb here is what the cluster looks like in GKE, whenever the pre-emptible node gets shutdown, these pods don't go away automatically  : 

image

**Comment by ahmetb** [comment]
That sounds like a problem with whatever controller is scheduling those pods (kube-controller-manager seems to be the case here). There shouldn't be a plugin needed to clean up Pods that are managed by a controller.

**Comment by shardulsrivastava** [comment]
@ahmetb agreed this should be handled by the `kube-controller-manager`, however that's not the case in AWS and GKE, that results into periodic checks for these pods and manual cleanup, this plugin attempts to automate that.

**Comment by ahmetb** [comment]
I am not sure I agree. Plugins are not automation tools, they're executed manually by kubectl users, mostly interactively. That's not automation. 

What you're running into might be a bug and accepting a plugin for this sort of situation doesn't make a lot of sense. I recommend you follow up about this somewhere instead of publishing a long term plugin here. 

You can still distribute your plugin via Krew using custom indexes if you want: https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes/ That way users can still install your plugin via Krew, but they'll be downloading the plugin manifest from your repository instead of krew-index. 

/close

**Pull request closed without merging**
