### PR TITLE
add dtlogin v1.0.0

### PR DESCRIPTION
**Pull request by devopstales**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Can you elaborate how's this different than oidc-login plugin?

**Comment by devopstales** [comment]
HI @derailed 
oidc-login plugin communicate with the openid provider and generates a config for the user. To do so It needs its own configuration. It is very inconvenient for the users to create this config and it stores sensitive data. My solution has a server component running in the kubernetes that handles the generation of the kubectl config (based on JWT token and its config stored in kubernetes) and push back this to the kubectl plugin. In my solution the user dose not need to bother with local configuration and dose not see the sensitive data in it.

**Comment by ahmetb** [comment]
I'm a bit hesitant to assign generic names like "login" or "oidc"/"openid-connect" because there can be multiple ways of doing the same thing, and we don't want the first-comer advantage to take over the name. For example, the community has plugins:
- https://github.com/clastix/kubectl-login
- https://github.com/Bisnode/kubectl-login
- https://github.com/TremoloSecurity/kubectl-login
- https://github.com/Financial-Times/kubectl-login
- https://github.com/david972/kubectl-login
- https://github.com/zjj2wry/kubectl-login
which is a great testament to what such generic terms mean different things to different people.

In this case, your project requires custom set up:

```
    1) You need to install the openid-connect server component by helm:
        helm repo add devopstales https://devopstales.github.io/helm-charts
```

which is how _you_ solve this OIDC login problem, and that's why I'm hesitant to assign this name to this submission.

If you can reconsider your name, I think we can be open to accepting this. (Also the tests are failing due to bad checksum.)

/kind gray-area
/hold

**Comment by devopstales** [comment]
Hi @ahmetb I understanding your argument, but if i add my name to the plugin like `kubectl devopstales-oidc-login` we ending up with a long  sub command name, that is wary inconvenient. If I can choose it would be just  `kubectl login`. My other problem with your argument, that there is a plugin in krew called `oidc-login`.

**Comment by ahmetb** [comment]
- I explained why we don't people just choose "kubectl login".
- oidc-login plugin is actually a tool named kubelogin and they had to change their name because we didn't allow "login". 
- Knowing what we know today, "oidc-login" could also have been a bad choice. Yet, oidc-login seems to be a more generic solution that works today.

We encourage developers to pick more unique names that have less chance of being used by other submissions in the same realm.

**Comment by ahmetb** [comment]
Alternatively can still distribute your plugin via Krew using custom indexes: https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes/ That way users can still install your plugin via Krew, you get to choose your name, but they'll be downloading the plugin manifest from your repository instead of krew-index.

**Comment by devopstales** [comment]
@ahmetb I created my own index but, that is not the same. I will change the name to  `dtlogin`. But I think it is a double stander If the owner of the oidc-login plugin dind't need to change name.

**Comment by ahmetb** [comment]
/lgtm
/approve
Thanks!

**Pull request merged**
