### PR TITLE
Add CLI for RHACM

### PR DESCRIPTION
**Pull request by itdove**
Signed-off-by: Dominique Vernier <dvernier@redhat.com>

### CODE REVIEW

**Comment by itdove** [comment]
I submitted the CLA, how to rerun 
cla/linuxfoundation ?

**Comment by corneliusweig** [comment]
Not sure what the problem is here. Do you intend to resubmit, or have you changed your mind?

**Comment by itdove** [comment]
@corneliusweig Waiting feedback from my management on the CLA that is required to sign.

**Pull request closed without merging**
