### PR TITLE
New version v1.3.1 of Kyverno

### PR DESCRIPTION
**Pull request by realshuting**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/kyverno.yaml is not a straightforward version bump: could not find the old/new version spec in the diff

**Comment by realshuting** [comment]
@ahmetb One more to add:
````
➜  krew-index git:(update_kyverno_v1.3.1) validate-krew-manifest -manifest ./plugins/kyverno.yaml
I0120 16:51:09.509899   72872 main.go:67] reading file "./plugins/kyverno.yaml"
I0120 16:51:09.511909   72872 main.go:84] structural validation OK
I0120 16:51:09.512136   72872 main.go:92] all spec.platform[] items are used
I0120 16:51:09.512332   72872 main.go:98] no overlapping spec.platform[].selector
I0120 16:51:09.512355   72872 main.go:102] installing spec.platform[0]
I0120 16:51:13.861103   72872 main.go:106] installed  spec.platforms[0]
I0120 16:51:13.861146   72872 main.go:102] installing spec.platform[1]
I0120 16:51:20.225372   72872 main.go:106] installed  spec.platforms[1]
I0120 16:51:20.225407   72872 main.go:102] installing spec.platform[2]
I0120 16:51:26.341738   72872 main.go:106] installed  spec.platforms[2]
2021/01/20 16:51:26 all 3 spec.platforms installed fine
````

**Comment by realshuting** [comment]
Kindly ping @ahmetb, is this good to merge?

**Comment by ahmetb** [comment]
Apologies, I thought I merged this.

**Comment by realshuting** [comment]
Thanks @ahmetb !

**Pull request merged**
