### PR TITLE
update minio.yaml sha256sum

### PR DESCRIPTION
**Pull request by harshavardhana**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/minio.yaml` is not a straightforward version bump: could not find the old/new version spec in the diff

**Comment by ahmetb** [comment]
@harshavardhana what's going on here? the checksums should not be changing unless there's a version bump. 

updating the manifest without updating the version could trigger some bug and brick people's local installations, so I'm not sure if we can confidently roll this forward.

**Comment by harshavardhana** [comment]
> @harshavardhana what's going on here? the checksums should not be changing unless there's a version bump.
> 
> updating the manifest without updating the version could trigger some bug and brick people's local installations, so I'm not sure if we can confidently roll this forward.

@ahmetb looks like the previous sha256sums were wrong and it was merged without verification.  I am just fixing them with correct sha256sums.

**Comment by ahmetb** [comment]
You're right. ￼i don't see the GitHub action running. That's unexpected. @chriskim06 @corneliusweig any theories? I wonder if it could be a timing issue (tide works fast enough before GitHub Actions kick in and post a "pending" status).

**Comment by corneliusweig** [comment]
I recently found that I had to approve a CI run, which was not the case previously. Could it be that this is breaking us?

**Comment by harshavardhana** [comment]
> You're right. ￼i don't see the GitHub action running. That's unexpected. @chriskim06 @corneliusweig any theories? I wonder if it could be a timing issue (tide works fast enough before GitHub Actions kick in and post a "pending" status).

It may be related with "first time contributors" since whenever I submit the CI/CD runs fine.

**Comment by harshavardhana** [comment]
I hope we can merge this PR soon while y'all investigate a potential issue with automated merges. 

Without this change merged things are breaking on our end.

**Comment by harshavardhana** [comment]
Anything that I can do to get this merged? @ahmetb @corneliusweig

**Comment by harshavardhana** [comment]
> Anything that I can do to get this merged? @ahmetb @corneliusweig

@ahmetb @corneliusweig ping

**Comment by harshavardhana** [comment]
No longer needed since we did v4.2.4 https://github.com/kubernetes-sigs/krew-index/pull/1505

**Pull request closed without merging**
