### PR TITLE
add kubectl-link plugin

### PR DESCRIPTION
**Pull request by umutbasal**
Repo: https://github.com/umutbasal/kubectl-link
kubectl-link simplifies accessing your kubernetes pods and services by automatically creating port-forwards on demand

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Thanks for the submission. We have quite a few similar plugins that do something with port-forward or wireguard. Do you mind checking if there's not one already merged?

**Comment by umutbasal** [comment]
I’ve reviewed 6 plugins related to proxy, port forward and wireguard. They primarily create a pod inside the cluster for proxying or port-forward a given list of resources or IPs.

**kubectl link** differs in;

- It creates a tun device on the local machine to provide VPN like experience with dns and routing.
- Port forwarding is handled automatically by network connections doesn’t need a list of resource names.
- Doesn’t rely on deploying anything in the cluster.

I believe it doesn’t overlap with existing plugins

**Comment by ahmetb** [comment]
Also, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

/lgtm
/approve
Thanks!

**Pull request merged**
