### PR TITLE
Add olly to krew plugins

### PR DESCRIPTION
**Pull request by Sanskarzz**
Add olly to krew plugins

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by Sanskarzz** [comment]
@chriskim06 Can you please guide me what is exact error with the CI

**Comment by chriskim06** [comment]
the archive from your repository unpacks to an executable called `kubectl-olly_v1.0.0_darwin_amd64` which doesnt match your `bin`. please take a look through our [docs on plugin manifests](https://krew.sigs.k8s.io/docs/developer-guide/plugin-manifest/).

on a separate note, this plugin seems to just invoke this olly chatbot which doesnt really enhance kubectl in any way. i couldnt really find too much about it but saw from here https://www.cloudraft.io/blog/olly-ai-powered-observability-assistant that it seems to be an ai chatbot centered around cloud native technology.

we dont usually accept plugins like this into our central index but you can still distribute your plugin via custom indexes. here are some docs for [hosting custom indexes](https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes/) and [how people can use them](https://krew.sigs.k8s.io/docs/user-guide/custom-indexes/).

**Comment by Sanskarzz** [comment]
@chriskim06 Thanks for the help we are going with custom index installation.

**Pull request closed without merging**
