### PR TITLE
Add plugin gateway

### PR DESCRIPTION
**Pull request by tafkam**
Hi!

kubectl krew install --manifest=gateway.yaml --archive=kubectl-gateway_linux_amd64.tar.gz
Installing plugin: gateway
Installed plugin: gateway
\
 | Use this plugin:
 |      kubectl gateway
 | Documentation:
 |      https://github.com/tafkam/kubectl-gateway
/

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Thanks for the submission. The name is too generic and is a first party concept in Kubernetes ecosystem.  We don't assign such names to a particular first comer unless they're an official Kubernetes project plugin.

Please refer to the naming guide in Krew docs. 
/hold

**Comment by tafkam** [comment]
That's alright. I would contribute if I had a clue about creating an official kubernetes kubectl plugin.😀 I guess that's not easy to achieve with the organizational overhead.
Would a rename of the plug-in to "manage-gateway" suffice?

**Comment by ahmetb** [comment]
I recommend proposing a plugin like this to the kubectl project. There are builtin commands like `kubectl create <resource>` and if that is still a pattern actively pursued, it's worth considering.

Overall I'm not sure if this is a plugin that adds value in the centralized krew-index:
- We could have a plugin/cmd for every single resource, but this largely doesn't make sense because Kubernetes already has a resource-agnostic way to manage every type of resource (resource manifests and kubectl/kustomize etc)
- The plugin installs/uninstalls CRDs, which again, I'm not sure if it's a good idea. Why would the users not use YAMLs declaratively and instead manage Gateway resource or parts of it declaratively?

I don't think this is how the user community manages resources? In that case, I don't see the value it adds broadly to the kubectl users.

You can still distribute your plugin via Krew using [custom indexes](https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes/). (Users will be downloading the plugin manifest from your repository instead of krew-index.)

**Comment by tafkam** [comment]
> I recommend proposing a plugin like this to the kubectl project. There are builtin commands like `kubectl create <resource>` and if that is still a pattern actively pursued, it's worth considering.

True, but the Gateway API is still shipped outside of Kubernetes as CRDs, until someday when it's mature enough. I guess that will stand in the way of directly adding functionality to kubectl.

> Overall I'm not sure if this is a plugin that adds value in the centralized krew-index:
> 
> * We could have a plugin/cmd for every single resource, but this largely doesn't make sense because Kubernetes already has a resource-agnostic way to manage every type of resource (resource manifests and kubectl/kustomize etc)

Also, agreed. The Gateway API is relatively new though. I see value in fiddling around with it (like "kubectl create ingress") to increase adoption. Nobody in the right mind would setup Ingress in production with kubectl. Same with Gateway API objects.

> * The plugin installs/uninstalls CRDs, which again, I'm not sure if it's a good idea. Why would the users not use YAMLs declaratively and instead manage Gateway resource or parts of it declaratively?

As mentioned before, this plugin doesn't aim to be a replacement for a more serious declarative deployment, which should be handled with GitOps, where you shouldn't need kubectl at all.

My main use-case for starting this plugin is not fully implemented yet. I started with the basics to "get going" with the Gateway API and implemented some low hanging fruit with the current functionality. The main function of this plugin will be "patching" (adding, removing, copying with modifications) segments of (mostly) HTTPRoutes to shift traffic (e.g. with defined headers) to another version of a (micro-)service deployment for development purposes. 
Using declarative/GitOps managed resources for "I quickly want to spin up my new microservice featurebranch to test it in a fully deployed environment with hundreds of other microservices" is cumbersome, when you have to modify hundreds or thousands of GitOps managed HTTPRoutes. Using a script or pipeline or devspace or whatever non-declarative way to make those changes with a kubectl plugin makes it easy though.

> I don't think this is how the user community manages resources? In that case, I don't see the value it adds broadly to the kubectl users.

Agreed, the term "manage" in the proposed renaming might be misleading.

> You can still distribute your plugin via Krew using [custom indexes](https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes/). (Users will be downloading the plugin manifest from your repository instead of krew-index.)
> 
> /kind gray-area

**Comment by tafkam** [comment]
Im gonna close this until the plugin isn't vaporware anymore, and maybe I'll find a better name on the way :) Thank you for your efforts @ahmetb!

**Pull request closed without merging**
