### PR TITLE
Add otel

### PR DESCRIPTION
**Pull request by agardnerIT**
# This PR

- Adds the `otel` plugin

# This Plugin

Uses [tracepusher](https://github.com/agardnerit/tracepusher) to generate [OpenTelemetry](https://opentelemetry.io) traces for `kubectl` commands.

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Hi, unless this is an official otel project, we cannot grant this name to your plugin.

**Comment by agardnerIT** [comment]
`Hi, unless this is an official otel project, we cannot grant this name to your plugin.`

Why? Nothing in the plugin naming guide forbids this? The name `otel` describes what the plugin does. `otel` is an abbreviation. I would understand if it was called `opentelemetry`.

What _would_ a valid plugin name be? `span`? `tp`? `tracepusher`? `tracer`?

`kubectl trace` is a plugin using `bpftrace` and that was excepted?

**Comment by ahmetb** [comment]
> I would understand if it was called `opentelemetry`.

It just so happens `otel` is practically the de facto name for OpenTelemetry project though?

You'll find inconsistencies before we started enforcing this. We strive to not to grant first-comer advantage to project/vendor names --or terms like `trace` that are fairly common in this domain and might  be assigned to more than one project.

It's not too hard to be creative and still have natural-sounding cmds here like: `kubectl traced`, `with-trace`, `with-otel`, `with-telemetry`, ...

**Comment by agardnerIT** [comment]
@ahmetb I've spoken to @austinlparker (an OpenTelemetry maintainer) and he stated that [he doesn't believe](https://cloud-native.slack.com/archives/CJFCJHG4Q/p1691885218094519) the project reserves `otel / OTEL` or any variant for use. So we should be OK to proceed here, right?

**Comment by austinlparker** [comment]
We don't reserve it from a trademark perspective, certainly.

**Comment by austinlparker** [comment]
I would say that I'm not super familiar with this PR but it seems like it only pushes traces? I would probably suggest more specific naming since OpenTelemetry supports metrics, traces, logs, etc.

**Comment by ahmetb** [comment]
Yeah, otel really isn't a good name for this plugin. It's the means to an end, I think we can get creative and find something better here that doesn't give the impression that this is the official kubectl plugin for otel.

**Comment by agardnerIT** [comment]
Correct, this plugin (currently) emits only traces, but there's no reason it couldn't emit metrics and logs (good enhancement).

In terms of naming, `strace` and `trace` are both already taken. What about `oteltrace`?

**Comment by ahmetb** [comment]
I'll suggest a couple more alternatives that are less likely to be taken away by anyone else:

    kubectl traced 
      e.g. kubectl traced get pods 

    kubectl otrace

**Comment by ahmetb** [comment]
Hi, @agardnerIT I've reviewed the source code of the plugin and basically it's setting a couple of environment variables around kubectl around using another command to execute kubectl. Typically we don't allow plugins that can be achieved with one-liners, and this seems to be roughly that. 
You can still distribute your plugin via Krew using custom indexes: https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes/ That way users can still install your plugin via Krew, but they'll be downloading the plugin manifest from your repository instead of krew-index.
/kind gray-area
/close

**Pull request closed without merging**
