### PR TITLE
feat: adding conditioner plugin

### PR DESCRIPTION
**Pull request by ddymko**
Hey there 👋 

Looking to add in the [conditioner](https://github.com/devbytes-cloud/conditioner) plugin to the krew index. This plugin lets you add, remove, update conditions on a node

- [X] Make sure you read the Plugin Naming Guide: https://krew.sigs.k8s.io/docs/developer-guide/develop/naming-guide/
- [X] Verify you can install your plugin locally: kubectl krew install --manifest=[...] --archive=[...]

Validation of local install 

```sh
☁  Downloads  cat conditioner.yaml

apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: conditioner
spec:
  version: v1.1.1
  platforms:
    - bin: kubectl-conditioner.exe
      uri: https://github.com/devbytes-cloud/conditioner/releases/download/v1.1.1/conditioner_Windows_x86_64.zip
      sha256: 66ea9cf3bd8e0caec32b5dffac2573a3df3ac96a3899012f7bd9f08a53a1c15d
      selector:
        matchLabels:
          os: windows
          arch: amd64
    - bin: kubectl-conditioner.exe
      uri: https://github.com/devbytes-cloud/conditioner/releases/download/v1.1.1/conditioner_Windows_arm64.zip
      sha256: 6a444f6533a695af37078760b36e3fa9b9cc27e80d4c1314517a9ba6dfe4b3b0
      selector:
        matchLabels:
          os: windows
          arch: arm64
    - bin: kubectl-conditioner
      uri: https://github.com/devbytes-cloud/conditioner/releases/download/v1.1.1/conditioner_Linux_x86_64.tar.gz
      sha256: 5a4d89f8968f24137aa784d41879b4a43e4b5b5d659e703429addd3d843ff3a2
      selector:
        matchLabels:
          os: linux
          arch: amd64
    - bin: kubectl-conditioner
      uri: https://github.com/devbytes-cloud/conditioner/releases/download/v1.1.1/conditioner_Linux_arm64.tar.gz
      sha256: ae777193dee428098af50b545eeec7b5fdf3832950d3226a1a8be86ed2f19b16
      selector:
        matchLabels:
          os: linux
          arch: arm64
    - bin: kubectl-conditioner
      uri: https://github.com/devbytes-cloud/conditioner/releases/download/v1.1.1/conditioner_Darwin_x86_64.tar.gz
      sha256: 5e32b7462321c309b284c00df194db6a2707b7e3f6123b9c3888c587d14f30f0
      selector:
        matchLabels:
          os: darwin
          arch: amd64
    - bin: kubectl-conditioner
      uri: https://github.com/devbytes-cloud/conditioner/releases/download/v1.1.1/conditioner_Darwin_arm64.tar.gz
      sha256: 23077822cb334df87d50409c64ef4f5ac554a686b60d9760aaa5f6d8660278d8
      selector:
        matchLabels:
          os: darwin
          arch: arm64
  shortDescription: Add, update, or remove conditions on Kubernetes nodes
  homepage: https://github.com/devbytes-cloud/conditioner
  description: Conditioner allows you to add, update, or remove conditions on Kubernetes nodes. It's a handy tool for cluster administrators to manage node status conditions effectively.
☁  Downloads  wget https://github.com/devbytes-cloud/conditioner/releases/download/v1.1.1/conditioner_Darwin_arm64.tar.gz
--2024-06-11 08:03:11--  https://github.com/devbytes-cloud/conditioner/releases/download/v1.1.1/conditioner_Darwin_arm64.tar.gz
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/758238328/b47245c7-15fa-454d-a6c7-631adf42f713?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240611%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240611T120311Z&X-Amz-Expires=300&X-Amz-Signature=a224c997bf3c76c092a5ba563397759ed02335d76bf4786b9d4ed764df9e7918&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=758238328&response-content-disposition=attachment%3B%20filename%3Dconditioner_Darwin_arm64.tar.gz&response-content-type=application%2Foctet-stream [following]
--2024-06-11 08:03:11--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/758238328/b47245c7-15fa-454d-a6c7-631adf42f713?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240611%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240611T120311Z&X-Amz-Expires=300&X-Amz-Signature=a224c997bf3c76c092a5ba563397759ed02335d76bf4786b9d4ed764df9e7918&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=758238328&response-content-disposition=attachment%3B%20filename%3Dconditioner_Darwin_arm64.tar.gz&response-content-type=application%2Foctet-stream
Resolving objects.githubusercontent.com (objects.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to objects.githubusercontent.com (objects.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10989534 (10M) [application/octet-stream]
Saving to: ‘conditioner_Darwin_arm64.tar.gz’

conditioner_Darwin_arm64.tar.gz                          100%[=================================================================================================================================>]  10.48M  --.-KB/s    in 0.1s

2024-06-11 08:03:11 (71.9 MB/s) - ‘conditioner_Darwin_arm64.tar.gz’ saved [10989534/10989534]

☁  Downloads  kubectl krew install --manifest=conditioner.yaml --archive=conditioner_Darwin_arm64.tar.gz
Installing plugin: conditioner
Installed plugin: conditioner
\
 | Use this plugin:
 | 	kubectl conditioner
 | Documentation:
 | 	https://github.com/devbytes-cloud/conditioner
/
```

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
I can accept this plugin, but fundamentally I think the tool is doing a "name grab" and is a bit limited-purpose, since it can only update `Node` conditions and nothing else. (I'm not sure if it's even feasible to update `conditions` fields of other types holistically since they all don't have the same shape/semantics.) That's why I'm conflicted a bit from naming and versatility/usefulness perspective.

/kind naming
/hold

**Comment by ddymko** [comment]
@ahmetb thanks for taking the time to look at this!

You mention that this is a "name grab". I was trying to follow the [developer guide](https://krew.sigs.k8s.io/docs/developer-guide/develop/naming-guide/) and give a somewhat a unique name to the plugin. Figured `conditioner` would be unique enough as I was approaching this as a shampoo/conditioner (thought I was being clever 😅) 

Would you suggest that a name change would be more appropriate here? 

> since it can only update Node conditions and nothing else.

Just to be devils advocate here. Looking through the krew index there are a lot of limited scoped plugins on the krew index such as [ctx/ns](https://github.com/ahmetb/kubectx) and these are plugins I use everyday.

---

**Comment by ahmetb** [comment]
I think I initially overreacted, sorry. If the name were "conditions" but it was doing only working on some resource conditions, it would've been a generic name grab situation limiting future assignment of the name. This is fine since the name is unique enough to not collide. 

/lgtm
/approve
/hold cancel


Also, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

**Pull request merged**
