### PR TITLE
Add kollama plugin

### PR DESCRIPTION
**Pull request by nekomeowww**
The `ollama` plugin from `ollama-operator` is considered generally suitable for users to try out, and the corresponding [`ollama-operator`](https://github.com/nekomeowww/ollama-operator) has a [detailed documentation sites](https://ollama-operator.ayaka.io/pages/en/) to share the usage, use case, helpers for users to learn about.

It

- followed the `kubebuilder` best practice,
- followed the `krew` naming conventions,
- uses recommended `goreleaser` and `krew` release bot GitHub Actions as part of the CI/CD workflow,
- uses all `k8s.io` repo, packages to implement the functionalities.

Already tested across platforms it supported.

The [`ollama-operator`](https://github.com/nekomeowww/ollama-operator) is part of the ecosystem of [`ollama`](https://github.com/ollama/ollama), a tool to easily run and deploy large language models. The [`ollama-operator`](https://github.com/nekomeowww/ollama-operator) itself is planning to have a PR to include it as one of the community projects under [`ollama`](https://github.com/ollama/ollama)'s README.

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Thanks for the submission. The biggest concern I have is around naming. You are requesting the name "ollama" which is a name of a larger project, however the ollama-operator repository belongs only to you. It's unclear to me if there's any official recognition to your repository. I'm trying to prevent the first-comer's advantage and reserve the name to the official organization.

**Comment by nekomeowww** [comment]
I have added `ollama-operator` and introduced the `kollama` CLI to the community: [docs: added Ollama Operator into README.md as one of community projects](https://github.com/ollama/ollama/pull/3792), haven't got any caught from official.

How about I change it to the same naming of `kollama` (stands for **k**ubernetes **ollama**)? It's totally ok for me!

Which in the way with no conflicts, and keep the name for the original community to decide, and also for users to clearly understand this is not the same product.

**Comment by nekomeowww** [comment]
> Thanks for the submission. The biggest concern I have is around naming. You are requesting the name "ollama" which is a name of a larger project, however the ollama-operator repository belongs only to you. It's unclear to me if there's any official recognition to your repository. I'm trying to prevent the first-comer's advantage and reserve the name to the official organization.

Updated to `kollama`. Could you please review it again?

**Comment by ahmetb** [comment]
`ollama` name is fine too as long as the project is recognized in the community as the de facto way of running the Ollama on Kubernetes.


> How about I change it to the same naming of `kollama` (stands for **k**ubernetes **ollama**)? It's totally ok for me!

`k*` prefix might be redundant in this case. We similarly [discourage](https://krew.sigs.k8s.io/docs/developer-guide/develop/naming-guide/) people from using `kube*` prefix.

**Pull request merged**
