### PR TITLE
[plugin] kubectl configrep

### PR DESCRIPTION
**Pull request by loomsen**
This PR introduces `kubectl configrep` plugin. It let's you find configmaps in a namespace or across the cluster, that match a certain pattern. Like `grep -l` for configmaps.

### CODE REVIEW

**Comment by loomsen** [comment]
I signed it.

**Comment by loomsen** [comment]
I signed it.

**Comment by ahmetb** [comment]
Thanks for your submission. I'm seeing little utility for this plugin.
It seems to be a small script wrapper for something rather simple such as:

```
for c in $(kubectl get configmaps --all-namespaces -o=name); do
    kubectl get "$c" --jsonpath='$.spec.*~' | grep KEYWORD
done
```

Usually we tend to not accept these sort of plugins, especially if they don't have an obvious use case.

**Comment by loomsen** [comment]
OK no worries.

**Comment by ahmetb** [comment]
You can still distribute your plugin via Krew using custom indexes: https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes/ That way users can still install your plugin via Krew, but they'll be downloading the plugin manifest from your repository instead of krew-index.

**Pull request closed without merging**
