### PR TITLE
add pod-viewer plugin

### PR DESCRIPTION
**Pull request by HamzaZo**
Adding a new plugin called `pod-viewer`
`pod-viewer` provides you with a full view of Kubernetes pod with information such as conditions, events, logs, etc.

### CODE REVIEW

**Comment by HamzaZo** [comment]
I signed it

**Comment by ahmetb** [comment]
/assign @corneliusweig 
IIRC there are quite a few plugins already like this.

**Comment by HamzaZo** [comment]
@ahmetb  Until now I didn't see a plugin that gives the whole output, that's why I started developing the `pod-viewer`. However, if you suggest any enhancement, I'm all ears

**Comment by ahmetb** [comment]
We tend to not accept plugin if there's no sufficient value add. If all you're doing is showing describe+logs, I think it falls into that territory. 

You can still distribute your plugin via Krew using custom indexes: https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes/ That way users can still install your plugin via Krew, but they'll be downloading the plugin manifest from your repository instead of krew-index.

**Pull request closed without merging**
