### PR TITLE
adding kubectl select to krew index.

### PR DESCRIPTION
**Pull request by n3wscott**
- select stands for `select a context for kubectl`.
- installed tested via ` kubectl krew install --manifest=plugins/select.yaml`

### CODE REVIEW

**Comment by ahmetb** [comment]
(My comment based on the description) Since the well-known kubectx tool is already a plugin here, named `ctx`, it's unlikely we'll go ahead with this. We have #351 as the precedent here (which we've closed, as well).

/hold
/cc @corneliusweig 
for additional review if I'm missing anything (if not, we can /close)

**Comment by n3wscott** [comment]
Does ctx have a menu?? You should try it. 😜😜

**Comment by ahmetb** [comment]
Yeah kubectx has an interactive menu with support for arrow keys and fuzzy string search. Further, it can rename contexts, delete contexts and switch back and forth using `-` syntax. You should try it. 😉😉

**Comment by n3wscott** [comment]
OH SWEET!! ok I will try it. I hacked up kubectl-select several months ago when I could not find one, but if there is a better one, AWESOME.

**Comment by n3wscott** [comment]
hm, how do I get the menu? 

```(╯°□°)╯︵  kubectl ctx
d2k
d2k-admin
docker-desktop
docker-for-desktop
mink
[01:33:06] snichols@snichols-a02 ~/go/src/github.com/kubernetes-sigs/krew-index (select)
(╯°□°)╯︵  kubectl ctx --help
USAGE:
  kubectl ctx                       : list the contexts
  kubectl ctx <NAME>                : switch to context <NAME>
  kubectl ctx -                     : switch to the previous context
  kubectl ctx -c, --current         : show the current context name
  kubectl ctx <NEW_NAME>=<NAME>     : rename context <NAME> to <NEW_NAME>
  kubectl ctx <NEW_NAME>=.          : rename current-context to <NEW_NAME>
  kubectl ctx -d <NAME> [<NAME...>] : delete context <NAME> ('.' for current-context)
                                  (this command won't delete the user/cluster entry
                                  that is used by the context)

  kubectl ctx -h,--help             : show this message

```

**Comment by n3wscott** [comment]
when I get some time, maybe I can look into adding the menu to this version. I don't want two, happy to upstream...

**Comment by ahmetb** [comment]
https://kubectx.dev#interactive-mode

**Comment by corneliusweig** [comment]
As far as I can tell, `select` switches the context with a terminal UI.
`ctx` can already do that (albeit with `fzf` helper) so I see no reason why we should have two very similar options in `krew-index`. In fact, `ctx` has other big advantages:
- it has been honed by a large user-basis on all platforms
- it keeps record of the previous context for fast back-and-forth
- it's bash and therefore very lightweight

So let's not confuse our users and just stick to `ctx`. But thanks for submitting this anyway!

/close

**Pull request closed without merging**
