### PR TITLE
KUTTL Bump 0.7.1

### PR DESCRIPTION
**Pull request by kensipe**
Figured out the issues we were historically having... we don't support Darwin 32 bit...  
This is a simple bump to the latest KUTTL
AND removal of 32 bit darwin

Signed-off-by: Ken Sipe <kensipe@gmail.com>

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/kuttl.yaml is not a straightforward version bump: diff line 23 unrecognized for version bumps: [-    bin: "./kubectl-kuttl"]

**Comment by kensipe** [comment]
hmmm... looks like we may have more scripting issue (this file is script generated for us).   Checking....

**Comment by kensipe** [comment]
@ahmetb The CI indicates a checksum failure... 

```
	I1028 14:12:32.966609    4157 fetch.go:39] Fetching "https://github.com/kudobuilder/kuttl/releases/download/v0.7.1/kuttl_0.7.1_linux_x86_64.tar.gz"
	I1028 14:12:33.050349    4157 downloader.go:42] Reading archive file into memory
	I1028 14:12:33.050431    4157 downloader.go:47] Read 1474 bytes from archive into memory
	I1028 14:12:33.050446    4157 verifier.go:51] Compare sha256 (113f466992e7ee6a1e38c20121d27efe479cca1f794eb302077dfc761083efb9) signed version
	I1028 14:12:33.050493    4157 install.go:101] Deleting the download staging directory /tmp/krew-downloads132968896
	W1028 14:12:33.050553    4157 install.go:164] failed to install plugin "kuttl": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does not match, want: 113f466992e7ee6a1e38c20121d27efe479cca1f794eb302077dfc761083efb9, got 5dadaaf70eeb3acf8f599b0fb3f8e4829099b5658c3cbbded391dad5d0c92a74
```

However... `113f466992e7ee6a1e38c20121d27efe479cca1f794eb302077dfc761083efb9` which is the checksum in the plugin file (for this artifact) double checks on my machine.

```
curl -L -o kuttl_0.7.1_linux_x86_64.tar.gz "https://github.com/kudobuilder/kuttl/releases/download/v0.7.1/kuttl_0.7.1_linux_x86_64.tar.gz"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   657  100   657    0     0   3957      0 --:--:-- --:--:-- --:--:--  3957
100 10.3M  100 10.3M    0     0  1240k      0  0:00:08  0:00:08 --:--:-- 1309k
❯ shasum -a 256 kuttl_0.7.1_linux_x86_64.tar.gz
113f466992e7ee6a1e38c20121d27efe479cca1f794eb302077dfc761083efb9  kuttl_0.7.1_linux_x86_64.tar.gz
```
The above check was using Darwin.  Is there some differences or anything to be aware of here?

**Comment by chriskim06** [comment]
Seems like it was a random travis failure, I re-ran the job and it passed this time. Also I just removed the travis step since we're using github actions now.

/lgtm
/approve

**Comment by kensipe** [comment]
thanks @chriskim06 !

**Comment by kensipe** [comment]
@ahmetb I think it is just missing the approved label

**Comment by ahmetb** [comment]
/approve
🤔

**Comment by chriskim06** [comment]
oh weird, I wonder why it didn't work when I did it earlier

**Pull request merged**
