### PR TITLE
Add new plugin mexec

### PR DESCRIPTION
**Pull request by major1201**
Hi, this is a plugin to make a fast way to run kubectl exec/cp on multiple pods in parallel.

More detailed information: <https://github.com/major1201/kubectl-batch>.

### CODE REVIEW

**Comment by ahmetb** [comment]
Hi, unfortunately `batch` is a very much overloaded/common term in this area and we do not grant any specific plugin a generic name like that. I also recommend you find a name that better reflects `exec`/`cp` aspect of the tool, as the current name almost implies it's for "batch scheduling" (e.g. KBatch, Volcano...) or `foreach`/`mc` plugins that already exist in Krew.

Please reopen once you choose a different name.

/kind gray-area
/close

**Comment by major1201** [comment]
@ahmetb Thank you so much for your suggestion!  Is `mexec` (exec on Multiple pods) a more reasonable name?  Since I found a similar plugin `mtail`.  I'll recommit once you accept this name.

**Comment by major1201** [comment]
@ahmetb Glad to see your acceptance, I've renamed my repo and command name to `mexec` now

**Comment by ahmetb** [comment]
/lgtm
/approve
Please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

**Pull request merged**
