### PR TITLE
Add kopy plugin

### PR DESCRIPTION
**Pull request by giorgosdi**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Thanks for your submission. Since you've very recently authored this plugin, I'm hoping this feedback makes sense. We typically try to encourage composability of the plugins and kubectl. 

As you also noted in your repo, is your plugin basically a shorthand alias for:

    kubectl get KIND/NAME -n SRC --context SRC | kubectl neat | kubectl apply -f- -n DST --context DST

If so, I think we should probably not accept this plugin since it seems "copying" is a special case that can be achieved by  composing existing plugins with kubectl builtin commands. (For the record, `eksporter` plugin also exists and does nearly the same thing as `neat` plugin already.)

**Comment by giorgosdi** [comment]
Hey Ahmet, thanks for the quick reply. Yeah you could say that it also works as an alias. The main reasoning behind this is to avoid these long piped command (i.e you need 3 of the to accomplish what kopy is doing with 1).

If you still believe that its derivative of these two plugins, then im happy for you to close the PR 😄

**Comment by ahmetb** [comment]
/close 
since it's not a fit to the plugin model but more like an alias/bash func.

**Pull request closed without merging**
