### PR TITLE
Add ttsum plugin

### PR DESCRIPTION
**Pull request by eytan-avisror**
This plugin makes viewing taints/tolerations across cluster resources easier
ttsum = taint & toleration summary

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Thanks for the submission, looks good. I have a few points of feedback:

1. it would be better if you update the CLI --help messages to show name `kubectl ttsum` (right now, it shows `ttsum`)
2. please [import client-go auth plugins](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/#auth-plugins), otherwise the plugin won't work against some cloud clusters
3. `kubectl ttsum tolerations` command doesn't seem to be working well, I have many pods with tolerations like the following, but the tool shows `none`:

example pod spec:
```
  tolerations:
  - effect: NoSchedule
    key: CriticalAddonsOnly
  - effect: NoSchedule
    key: nvidia.com/gpu
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: nvidia.com/gpu
    operator: Exists
```

Also, after this PR is merged, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

**Comment by eytan-avisror** [comment]
> 

Those tolerations only show up on pods directly, the tool lists from deployment/daemonset/else spec
You will only see whats on deployment spec

**Comment by eytan-avisror** [comment]
Regarding the `--help` flag - for some reason cobra is only picking up a single word, i.e. you can use `ttsum` or `kubectl` which would show up:
```
ttsum helps summarize tainted nodes and tolerating resources

Usage:
  kubectl [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  taints      taints summarizes taints for nodes, and whether they will accept a toleration
  tolerations tolerations summarizes tolerations for a resource
  version     Version of ttsum

Flags:
  -h, --help   help for kubectl

Use "kubectl [command] --help" for more information about a command.
```

I'll release a fix with the added import and bump this up

**Comment by ahmetb** [comment]
/lgtm
/approve
Thanks!

**Comment by ahmetb** [comment]
> Those tolerations only show up on pods directly (probably added by admission controller), the tool lists from deployment/daemonset/else spec i.e. declarative ones, not dynamically added You will only see whats on deployment spec

btw I still don't understand this comment. if I'm running `kubectl ttsum tolerations v1 pods`, why would you care about the deployment/daemonset etc? I think the user would want to see the tolerations on those pods.

**Pull request merged**
