### PR TITLE
Update: plugins.md

### PR DESCRIPTION
**Pull request by MnrGreg**
Add node-restart to plugins.md

### CODE REVIEW

**Comment by corneliusweig** [comment]
Hey, thanks for being to thoughtful and submitting an update to the plugins list.

It looks like you create the table entry by hand. Can you please generate the file with our tool `go get sigs.k8s.io/krew/cmd/generate-plugin-overview`?

**Comment by MnrGreg** [comment]
@corneliusweig I've updated plugins.md with `generate-plugin-overview`. I didn't see this step in the developer guide. Did I miss it or does it still need to be added?

**Comment by ahmetb** [comment]
We’re hoping not everyone has to do that as we execute it somewhat regularly.

**Comment by corneliusweig** [comment]
@MnrGreg looks good now, thanks!

We don't expect submitters to update this list. We usually run that tool from time to time, but maybe we'll integrate it in our process.

/lgtm
/approve

**Pull request merged**
