### PR TITLE
Revert "release new version v1.6.10 of kyverno"

### PR DESCRIPTION
**Pull request by realshuting**
Reverts kubernetes-sigs/krew-index#2040

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this. If we don't respond within a day, feel free to ping us.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/kyverno.yaml` is not a straightforward version bump: version should move forward (`"v1.6.10"` vs `"v1.6.0"`)
/kind plugin-update

**Comment by ahmetb** [comment]
I am hesitant to accept this. Practically it might be fine since it just got merged. But theoretically this can brick installations.

Why do you need this/how did the release happen?

**Comment by realshuting** [comment]
/assign @chriskim06

This tag for the release is incorrect, we'd like to revert it and will submit a new PR with the right tag.

**Comment by ahmetb** [comment]
Just fyi this would not work for any other package manager. Once you put a release out, it's there, and you have to roll forward. 

/lgtm
/approve

**Comment by realshuting** [comment]
> Just fyi this would not work for any other package manager. Once you put a release out, it's there, and you have to roll forward.
> 
> /lgtm /approve

Good to know, thanks!

Sorry for the noise.

**Pull request merged**
