### PR TITLE
Bump outdated to 0.3.0

### PR DESCRIPTION
**Pull request by marccampbell**
Bump outdated plugin to v0.3.0 with support for specifying an alternate kubecontext as a flag

### CODE REVIEW

**Comment by corneliusweig** [comment]
I see that you chose `kubecontext` as the flag name. Would it be possible to use the standard flag name for that, which is just `context`? This will improve the usability, because users are already accustomed to that flag name.

Have you also considered using k8s.io/cli-runtime/pkg/genericclioptions for flags? This provides a lot of standard flags, but I'm not sure if this is viable in your case.

**Comment by marccampbell** [comment]
Thanks @corneliusweig.  Makes sense to me, I'll update

**Comment by corneliusweig** [comment]
Thanks, I'll put this on hold for now 
/hold

**Comment by marccampbell** [comment]
@corneliusweig Thanks for the link and pointer to the `genericclioptions` package. This worked great, and we now have the full pflag support added to this plugin.

**Comment by corneliusweig** [comment]
Looks great!
/lgtm
/approve

**Pull request merged**
