### PR TITLE
Added nodegizmo plugin

### PR DESCRIPTION
**Pull request by Kavinraja-G**
Team, 

I would like to add my kubectl-plugin `nodegizmo` in krew index. This is a small utility for your kubernetes nodes providing various features as mentioned [here](https://github.com/Kavinraja-G/node-gizmo#features). More to come 🚀

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by Kavinraja-G** [comment]
@ahmetb any comments on this PR would be great. TY!

**Comment by ahmetb** [comment]
Sorry for the latency here. The plugin does not seem to be working out-of-the box.

```
kubectl nodegizmo
2023/09/16 12:41:38 Error generating md docs for nodegizmo: open docs/nodegizmo_node_capacity.md: no such file or directory
```

Please ping again when the plugin actually works.

**Comment by Kavinraja-G** [comment]
@ahmetb -- Thanks for the review & pointing that issue. I had fixed the issue and update the PR!

**Comment by ahmetb** [comment]
@Kavinraja-G just had a chance to review. This plugin is a bit odd because it actually does things that other plugins do. (e.g. `ttsum`, `view-capacity`, `view-allocations`, `resource-capacity` and [`nsenter`](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/nsenter.yaml)). 

There are a few unique aspects such as integrating tighter with the cloud providers, showing machine sizes/OS image names, and `nodepool` functionality does not exist in any other plugin as far as I know (maybe `fleet` plugin has it, not sure). Because of this brand-new functionality, I'll approve it (otherwise we'd disallow this since plugin is a subset of other plugins).

But I'll recommend you to keep the plugin focused to fewer tasks and let other tools do each focused task better.

/hold cancel
/lgtm
/approve
Thanks!

Also, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

**Comment by Kavinraja-G** [comment]
Appreciate your detailed feedback about the plugin. Yup, I have more features in the pipeline that would be released in the upcoming weeks.
- Custom `nsenter` images where users bring in their own debugging image or I'm planning to maintain custom set of debugging tools images which can be leveraged as well.
- More sorting & filtering options in the node outputs
- Node health information etc., 

Will keep this thread updated with new releases.

And, yes I had already integrated automation around creating PRs whenever I release a new plugin version.

Thanks!

**Pull request merged**
