### PR TITLE
add pv-migrate plugin

### PR DESCRIPTION
**Pull request by utkuozdemir**
-----

**Checklist for plugin developers:**

- [x] Read the [Plugin Naming Guide](https://github.com/GoogleContainerTools/krew/tree/master/docs/NAMING_GUIDE.md) (for new plugins)
- [x] Verify the installation from URL or a local archive works (`kubectl krew install --manifest=[...] --archive=[...]`)

### CODE REVIEW

**Comment by utkuozdemir** [comment]
I signed it!

**Comment by ahmetb** [comment]
Do you think this would be a tool that people would use frequently? We’re actively trying to avoid one-off scripts to be distributed as plugins.

**Comment by utkuozdemir** [comment]
Hm, nope, it’s more of a one-off script. If you try to avoid those better leave this out - it’s fine.

**Comment by corneliusweig** [comment]
/remove-lifecycle stale
Still awaiting a final decision for plugin guidelines.

**Pull request closed without merging**
