### PR TITLE
Bump outdated to 0.3.3

### PR DESCRIPTION
**Pull request by marccampbell**
Bumping outdated to v0.3.3

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **doesn't** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/outdated.yaml is not a straightforward version bump: changing old version ("0.3.2") with new version ("0.3.3") in the url (https://github.com/replicatedhq/outdated/releases/download/v0.3.2/outdated_0.3.2_linux_amd64-0.3.2.tar.gz) did not result in the new url (https://github.com/replicatedhq/outdated/releases/download/v0.3.3/outdated_linux_amd64.tar.gz), expected: https://github.com/replicatedhq/outdated/releases/download/v0.3.3/outdated_0.3.3_linux_amd64-0.3.3.tar.gz

**Comment by marccampbell** [comment]
This is a simple version bump, but the previous version had a pretty ~ugly~ redundant download URI (the version number was 3x in the URL).

No plans to change this URI again, but wanted to take the chore of cleaning up this goreleaser URL in this one bump. 

Thanks for the review.

**Comment by ahmetb** [comment]
/lgtm
/approve

BTW are you possibly interested in maintaining your own index?
We are adding support for custom indexes.

**Comment by marccampbell** [comment]
@ahmetb I'd love to try the new index support, let's chat on slack!

**Pull request merged**
