### PR TITLE
gadget: Update description

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/gadget.yaml is not a straightforward version bump: could not find the old/new version spec in the diff

**Comment by corneliusweig** [comment]
I guess this is in response to https://github.com/kubernetes-sigs/krew-index/pull/628#issuecomment-636200418.

@ahmetb I suggested this wording, because `app` sounds somewhat implicit to me. Besides, the list of subcommands from here https://github.com/kinvolk/inspektor-gadget#how-to-use does not suggest that it's very app-specific, but rather a general swiss-army knife toolset. WDYT?

**Comment by ahmetb** [comment]
It seems like it’s pretty process-oriented so I’m good with this. 👍🏼

**Comment by mauriciovasquezbernal** [comment]
I'd say that it's container-oriented. Even if the "app" word is somehow implicit, "Gadgets for debugging and introspecting" sound like is missing something.

**Pull request merged**
