### PR TITLE
add plugin prof (fork of kubectl flame)

### PR DESCRIPTION
**Pull request by josepdcs**
[**kubectl-prof**](https://github.com/josepdcs/kubectl-prof) is a kubectl plugin that allows you to profile production applications with low-overhead by generating [FlameGraphs](http://www.brendangregg.com/flamegraphs.html) at the moment. More functionalities will be added in the future.

This is an open source fork of current plugin [kubectl-flame](https://github.com/yahoo/kubectl-flame) with several new features and bug fixes.

**Initial version 0.1.0**:
- Added support for CRIO as container runtime. Tested even on OpenShift.
- Simple logging support for better tracing in order to guess what are happening.
- Parametrized privileged mode and capabilities for the agent pod.
- Deep refactoring and clean code.

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by josepdcs** [comment]
I renamed original tool/repository kubectl-profle to new one named kubectl-perf (more specific).

**Comment by ahmetb** [comment]
sorry I left some comments at the old PR. please take a look and try to answer:
https://github.com/kubernetes-sigs/krew-index/pull/2102#issuecomment-1074133316
https://github.com/kubernetes-sigs/krew-index/pull/2102#issuecomment-1074134810

**Comment by josepdcs** [comment]
Hi, @ahmetb
Thanks for you comments. I answer you here too:

1.     Ok. I will rename again the plugin to kubectl-prof
2. Yes. The reason of forking is to do a completely rework of the flame plugin by adding more features

**Comment by josepdcs** [comment]
Hi @ahmetb ,

As sugested, I've already renamed the plugin from kubectl-perf to kubectl-prof.

**Comment by ahmetb** [comment]
@josepdcs thanks for your submission but I am still against accepting this without having a clear understanding of why this work cannot be done in the https://github.com/yahoo/kubectl-flame/ repository. Even plugin descriptions/usage strings are nearly identical. Have you made these feature proposals to the upstream repository or sent patches?

I know you added some new features in your fork, but I need you to understand the curators' perspective. If everyone forked a plugin of their choosing and added a couple of features on top of the fork, we would have to deal with 500 plugins where half of them are overlapping except with minor features. This neither helps us krew-index maintainers, nor the yahoo/kubectl-flame maintainers, nor you (as your users will choose kubectl-flame as it currently has more github stars etc). I am currently not understanding your motive.

I'm currently -1 on accepting this plugin as it sets a precedent for forking a project [for no apparent reason], makes the curation harder as it generates extra work for the same output for us, and makes it harder for a user to choose between two nearly identical plugins. I don't want to block your development as you are free to fork things and develop further, but I don't think I'm supportive of setting this precedent in this repo, and you can use https://krew.sigs.k8s.io/docs/developer-guide/custom-indexes/ to distribute your plugin instead.

/hold
/kind gray-area

**Comment by josepdcs** [comment]
Thanks, @ahmetb for your comments and I understand your reasoning. I'll still working in my development and, maybe, when it gets more advanced, I'll try out for publishing it in krew index again.

Regards,
Josep

**Pull request closed without merging**
