### PR TITLE
Add duplik8s plugin

### PR DESCRIPTION
**Pull request by Telemaco019**
The PR adds [duplik8s](https://github.com/Telemaco019/duplik8s) to the krew index.

> ✅ Make sure you read the Plugin Naming Guide: https://krew.sigs.k8s.io/docs/developer-guide/develop/naming-guide/
> ✅ Verify you can install your plugin locally: kubectl krew install --manifest=[...] --archive=[...]

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Review by Telemaco019 — COMMENTED** [review]
fix: indentation

**Comment by ahmetb** [comment]
Hi, thanks for your submission. Is this plugin basically a subset of the `dup` plugin? https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/dup.yaml

**Comment by Telemaco019** [comment]
Hey @ahmetb, thanks for the heads-up about the `dup` plugin!

I've given it a shot by swapping out `duplik8s` in my setup, but it didn’t quite hit the mark for me. The cool thing about `duplik8s` is that it automatically tweaks parts of the Pods spec to make them debug-ready, so I don’t have to manually mess with the settings. It’s super handy because I can plug it straight into [k9s](https://k9scli.io/) and start debugging pods with just one shortcut.

To me it seems like the two plugins tackle slightly different issues:
* `dup`: Focuses on debugging _Kubernetes resources_ by allowing you to clone them with custom overridden specs.
* `duplik8s`: Aims at debugging _containers_ by cloning Pods and tweaking their specs so you can easily pop open a shell in the containers.

What do you think?

**Comment by ahmetb** [comment]
Apologies for late review.
/lgtm
/approve
Also, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

**Pull request merged**
