### PR TITLE
Cluster snapshot plugin

### PR DESCRIPTION
**Pull request by fbrubbo**
https://github.com/fbrubbo/kubectl-plugins#kubectl-snapshot

### CODE REVIEW

**Comment by fbrubbo** [comment]
Done CLA

**Comment by ahmetb** [comment]
I can't find the source code for your plugin. It seems like you just checked in a binary to GitHub, which is not a great idea at all. Can you please provide the source code?

**Comment by corneliusweig** [comment]
I don't think we documented that plugins without source code cannot be accepted into `krew-index`.

**Comment by corneliusweig** [comment]
@fbrubbo I'm sorry, but we will not accept opaque binary plugins whose source code cannot be inspected.

If you want to open-source your work, feel free to re-submit your plugin afterwards.
/close

**Pull request closed without merging**
