### PR TITLE
Update score to v1.7.2

### PR DESCRIPTION
**Pull request by zegl**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/score.yaml is not a straightforward version bump: diff line 7 unrecognized for version bumps: [-  - selector:]

**Comment by zegl** [comment]
This is a simple version bump, but I've automated the process and some automatic formatting was included :)

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/score.yaml is not a straightforward version bump: diff line 7 unrecognized for version bumps: [-  - selector:]

**Comment by ahmetb** [comment]
@zegl thanks, also, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

/lgtm
/approve

**Comment by zegl** [comment]
@ahmetb Thanks for the tip, but I just setup some [custom automation](https://github.com/zegl/kube-score/blob/master/hack/krew-index.sh) for the same purpose. :)

**Comment by ahmetb** [comment]
Got it. Let’s hope it produces reproducibly ordered output that can be auto-merged. 👍🏼

**Pull request merged**
