### PR TITLE
Update virt (KubeVirt virtctl plugin package) to v0.28.0

### PR DESCRIPTION
**Pull request by dhiller**
See https://github.com/kubevirt/kubevirt/releases/tag/v0.28.0

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request seems to be a straightforward version bump.
I'll go ahead and accept it. :+1: Cheers.

/lgtm
/approve

**Comment by dhiller** [comment]
Hm, the [build is fine](https://travis-ci.org/github/kubernetes-sigs/krew-index/builds/674321680) but the check reporting doesn't seem to work ATM.

**Comment by dhiller** [comment]
@ahmetb sorry to bother, can you override here?

**Comment by ahmetb** [comment]
Travis CI seems to have stuck because it thinks your PR is a draft.
https://travis-ci.org/github/kubernetes-sigs/krew-index/builds/674321680

By the way have you considered [Automating plugin updates](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/)?

**Pull request merged**
