### PR TITLE
Add `armadactl` plugin

### PR DESCRIPTION
**Pull request by ShivangShandilya**
-  `armadactl` is a command-line tool used for managing jobs in the Armada workload orchestration system.
    It provides functionality for creating, updating, and deleting jobs, as well as monitoring job status and resource usage.
    
- [Armada](https://github.com/armadaproject/armada) is a CNCF Sandbox project. Armada is a multi-kubernetes-cluster batch job meta-scheduler.
  It helps organizations distribute millions of batch jobs per day across many nodes across many clusters.

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

Thanks for submitting your kubectl plugin to Krew!
One of the krew-index maintainers will review it soon. Note that the reviews for new plugin submissions may take a few days.

In the meanwhile, here are a few tips to make your plugin manifest better:
* Make sure your plugin follows the [best practices](https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/).
* Eliminate redundant wording form `shortDescription` (it should be max 50 characters).
* Try to word wrap your `description` to 80-character lines (no usage examples, please).

Thanks for your patience!
/kind new-plugin

**Comment by ahmetb** [comment]
Hi, thanks for your submission. The name `armadactl` basically suggests this tool is mostly designed for standalone use. We typically expect kubectl plugins to extend kubectl and feel a natural part of using kubectl. Not everything related to Kubernetes has to be a kubectl plugin. There are plenty of tools like minikube, helm, kind, istioctl) that are distributed standalone. 

Please elaborate why you want to distribute this tool as a kubectl plugin in addition to a standalone tool.

**Comment by kannon92** [comment]
> Hi, thanks for your submission. The name `armadactl` basically suggests this tool is mostly designed for standalone use. We typically expect kubectl plugins to extend kubectl and feel a natural part of using kubectl. Not everything related to Kubernetes has to be a kubectl plugin. There are plenty of tools like minikube, helm, kind, istioctl) that are distributed standalone.
> 
> Please elaborate why you want to distribute this tool as a kubectl plugin in addition to a standalone tool.

Armada is a sandbox project for running batch jobs accross multiple kubernetes clusters.  We deploy `armadactl` as a separate App but we would love to have it be part of Krew.  Our reason for including this in Krew is to allow users who use `kubectl` to also be able to use `kubectl armadactl`.

Karmada is a project focused on multicluster deployments.  We see that `karmadactl` is also a plugin in Krew so we figured it is okay to include cli for projects that are more than just a single kubernetes cluster.  Our goal is to allow `kubectl` users an easier way to interact with Armada.

**Comment by ahmetb** [comment]
I understand what Armada is, but why not distribute using other package managers?

Krew doesn't come pre-installed either and it's more likely your users have access to a package manager like Homebrew. As I explained plenty of first-party Kubernetes official projects like kind, Helm, minikube also don't distribute their CLIs as kubectl plugins (because they're not meant to be kubectl plugins).

This plugin doesn't extend kubectl experience either. That's why I don't think it's the right plugin to have in the centralized index.

**Comment by kannon92** [comment]
> I understand what Armada is, but why not distribute using other package managers?
> 
> Krew doesn't come pre-installed either and it's more likely your users have access to a package manager like Homebrew. As I explained plenty of first-party Kubernetes official projects like kind, Helm, minikube also don't distribute their CLIs as kubectl plugins (because they're not meant to be kubectl plugins).
> 
> This plugin doesn't extend kubectl experience either. That's why I don't think it's the right plugin to have in the centralized index.

Ah okay.  That makes us sad.  We will look into self-hosting then.  

We were hoping that since other projects like [Flyte](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/flyte.yaml), [Karmada](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/karmada.yaml) and [Kruise](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/kruise.yaml) are part of this index that it would be okay to include Armada on this list.  

We do distribute via other package managers but we wanted to look into Krew as an option for deploying `kubectl` plugins.  Anyway it is up to your discretion so please free to close if you think this is not valid for this index.

**Comment by ahmetb** [comment]
> We were hoping that since other projects like [Flyte](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/flyte.yaml?rgh-link-date=2023-08-01T15%3A30%3A29Z), [Karmada](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/karmada.yaml?rgh-link-date=2023-08-01T15%3A30%3A29Z) and [Kruise](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/kruise.yaml?rgh-link-date=2023-08-01T15%3A30%3A29Z) are part of this index that it would be okay to include Armada on this list.


Maybe I'm misunderstanding but those tools basically manage Kubernetes [custom] resources on clusters, and such tools are okay. We have plenty of those. 

In this case, is `armadactl` making requests to Kubernetes API and managing Kubernetes resources (e..g those that have apiVersion/kind etc), or is it mainly directly submitting config/manifests to another bespoke API of Armada? Because one of these look like it's part of the kubectl experience, the other one does not.

**Comment by kannon92** [comment]
> > We were hoping that since other projects like [Flyte](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/flyte.yaml?rgh-link-date=2023-08-01T15%3A30%3A29Z), [Karmada](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/karmada.yaml?rgh-link-date=2023-08-01T15%3A30%3A29Z) and [Kruise](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/kruise.yaml?rgh-link-date=2023-08-01T15%3A30%3A29Z) are part of this index that it would be okay to include Armada on this list.
> 
> Maybe I'm misunderstanding but those tools basically manage Kubernetes [custom] resources on clusters, and such tools are okay. We have plenty of those.
> 
> In this case, is `armadactl` making requests to Kubernetes API and managing Kubernetes resources (e..g those that have apiVersion/kind etc), or is it mainly directly submitting config/manifests to another bespoke API of Armada? Because one of these look like it's part of the kubectl experience, the other one does not.

I can see the distinction.  Our `armadactl` creates queues and jobs on the Armada API which takes a k8 pod.  We aren't using CRDs for these yet but we are trying to replace a similar behavior for k8 users.  We want to utilize our queueing solution for handling batch jobs if a single k8 cluster is not enough.  But you are correct in that it would be an Armada API object rather than a k8 api.  We do end up creating k8 pods on a k8 cluster but we have a layer of abstraction to avoid overloading a cluster with too many batch jobs.

**Comment by ahmetb** [comment]
/lgtm
/approve
Thanks!

Also, please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

**Pull request merged**
