### PR TITLE
Added ARM support and updated github username

### PR DESCRIPTION
**Pull request by rewanthtammana**
### Description

- Added ARM support to the plugin
- Updates github username in download URLs

Closes https://github.com/rewanthtammana/kubectl-fields/issues/2

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this. If we don't respond within a day, feel free to ping us.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/fields.yaml` is not a straightforward version bump: could not find the old/new version spec in the diff
/kind plugin-update

**Comment by rewanthtammana** [comment]
@ahmetb @corneliusweig @chriskim06 Can you please approve this PR?

**Comment by rewanthtammana** [comment]
@ahmetb I made the suggested changes!

**Comment by ahmetb** [comment]
/lgtm
/approve
Thanks!

**Pull request merged**
