### PR TITLE
[minio/direct-csi] upgrade to v1.2.1

### PR DESCRIPTION
**Pull request by wlan0**
- [X] Make sure you read the Plugin Naming Guide: https://krew.sigs.k8s.io/docs/developer-guide/develop/naming-guide/
- [X] Verify you can install your plugin locally: `kubectl krew install --manifest=[...] --archive=[...]`

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/direct-csi.yaml is not a straightforward version bump: could not find the old/new version spec in the diff

**Comment by ahmetb** [comment]
@wlan0 it seems you made a mistake.
Please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved. 
But if you make mistakes like these, they will not be.

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request seems to straightforward.
I'll go ahead and accept it. :+1: Cheers.

/lgtm
/approve

**Comment by wlan0** [comment]
> @wlan0 it seems you made a mistake.
Please consider setting up Krew release automation which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

@ahmetb Nice catch. I see the issue with manual updates. Your suggestion makes sense, we are going to set it up right away. For now, I've fixed this PR.

**Pull request merged**
