### PR TITLE
KUDO update to 0.8.0

### PR DESCRIPTION
**Pull request by bchatard**
* Update doc about initialization (cf. https://kudo.dev/docs/#install-kudo-into-your-cluster)
* drop windows support (cf. https://github.com/kudobuilder/kudo/releases/tag/v0.8.0-pre.0)

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **doesn't** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/kudo.yaml is not a straightforward version bump: diff line unrecognized for version bumps: [-      kubectl create -f https://raw.githubusercontent.com/kudobuilder/kudo/v0.4.0/docs/deployment/00-prereqs.yaml]

**Comment by bchatard** [comment]
I signed it

**Comment by corneliusweig** [comment]
/lgtm
/approve

Just curious: will you re-enable window support when https://github.com/kudobuilder/kudo/issues/893 is done?

**Comment by ahmetb** [comment]
I'm actually not sure about the ramifications of removing a platform from the list. This might've just broken the windows users who've installed this. :)

It would be good if we don't delete platforms in the future –unless kudo discontinued windows support indefinitely.

**Comment by corneliusweig** [comment]
Let's check this proper, so we definitely know for the future.

**Comment by bchatard** [comment]
> Just curious: will you re-enable window support when [kudobuilder/kudo#893](https://github.com/kudobuilder/kudo/issues/893) is done?

I hesitate when I remove the windows part. Maybe we can keep the Windows version on 0.7.5?

**Comment by ahmetb** [comment]
It’s probably too late now, and version mismatch wouldn’t be good.
Good thing this isn’t breaking people per the linked issue.  
But you should add it back once enabled.

**Comment by bchatard** [comment]
you're right. I will check the issue status and update this

thanks for your feedback :)

**Pull request merged**
