### PR TITLE
bump kubectl-neat to v2.0.1

### PR DESCRIPTION
**Pull request by itaysk**
as a quick workaround to an issue introduced by the recently released v2.0.0, I've also updated the usage example

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/neat.yaml is not a straightforward version bump: diff line 3 unrecognized for version bumps: [-    `$ kubectl neat get pod mypod -o yaml`]

**Comment by ahmetb** [comment]
Please consider setting up [Krew release automation](https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/) which helps you skip manually making updates to your Krew manifests on each new version and send a pull request. It’s a GitHub workflow bot that can run every time you push a new tag. Those PRs are automatically approved.

/lgtm
/approve

**Comment by itaysk** [comment]
Thanks @ahmetb, Actually I already have a very similar automation for generating the krew manifests based on a template. can you please elaborate on: "Those PRs are automatically approved"? As far as I understand the current pr wasn't automatically merged because it included a change to the template outside a simple version bump. Are these kind of changes also auto merged if using the krew action?

**Comment by ahmetb** [comment]
They aren't.

**Pull request merged**
