### PR TITLE
Fix file ending df-pv.yml -> df-pv.yaml

### PR DESCRIPTION
**Pull request by corneliusweig**
Right now, the plugin won't show up in `krew search`, and cannot be installed.

### CODE REVIEW

**Comment by corneliusweig** [comment]
/hold
I was trying out this plugin, but it did not seem to work on minikube. I've opened issue https://github.com/yashbhutwala/kubectl-df-pv/issues/2, so let's wait until the author responds to not confuse other users.

**Comment by ahmetb** [comment]
I already had to hotfix this directly because it was breaking all existing clients.
/close

**Comment by yashbhutwala** [comment]
My bad guys 😅

**Comment by corneliusweig** [comment]
Well, I'd say you found a bug in our CI ;-)

**Pull request closed without merging**
