### PR TITLE
Add debug plugin

### PR DESCRIPTION
**Pull request by aylei**
Hi there, thanks for reviewing my PR! Please don't hesitate to point out areas where I need to change.

Plugin [Home Page](https://github.com/aylei/kubectl-debug)

Signed-off-by: Aylei <rayingecho@gmail.com>

-----

**Checklist for plugin developers:**

- [x] Read the [Plugin Naming Guide](https://github.com/GoogleContainerTools/krew/tree/master/docs/NAMING_GUIDE.md) (for new plugins)
- [x] Verify the installation from URL or a local archive works (`kubectl krew install --manifest=[...] --archive=[...]`)

### CODE REVIEW

**Comment by ahmetb** [comment]
This name is too generic. Please choose something more unique and descriptive. Also there’s been a proposal to create an official debug command, which might be still going on: https://github.com/kubernetes/kubernetes/issues/45922

**Comment by ahmetb** [comment]
I agree `debug-container` or `debug-pod` is better (debug-pod would be my preference). Sadly first-class kubectl commands can claim vauge/broad terminology like "debug" but I think we should be more careful.

Does this cause a problem with your documentation etc. Are you planning to go make the name change there as well?

**Comment by aylei** [comment]
> Does this cause a problem with your documentation etc.
Not quite, I will add documents to explain the `krew` part about the slightly different name and it's a not a burden for me.

>  Are you planning to go make the name change there as well?
I prefer not, changing name can be troublesome for me and existing adopters.

**Comment by aylei** [comment]
I realize that I have to update some codes to support both `kubectl debug-pod` and `kubectl debug` command suggestions, so I will close this PR now and open another PR in the next release of my project.

**Comment by ahmetb** [comment]
Thanks! Expecting a new PR soon, happy to discuss what would be a more appropriate name.

**Pull request closed without merging**
