### PR TITLE
bump preflight and support-bundle to v0.9.14

### PR DESCRIPTION
**Pull request by divolgin**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **doesn't** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/preflight.yaml is not a straightforward version bump: changing old version ("0.9.13") with new version ("0.9.14") in the url (https://github.com/replicatedhq/troubleshoot/releases/download/v0.9.13/preflight_0.9.13_linux_amd64-0.9.13.tar.gz) did not result in the new url (https://github.com/replicatedhq/troubleshoot/releases/download/v0.9.14/preflight_linux_amd64.tar.gz), expected: https://github.com/replicatedhq/troubleshoot/releases/download/v0.9.14/preflight_0.9.14_linux_amd64-0.9.14.tar.gz

**Comment by ahmetb** [comment]
if you can send separate PRs for these plugins, they will be autoapproved. 
What do you think? Are you handwriting these patches? We’re working on an automation.

**Comment by divolgin** [comment]
@ahmetb thanks.  I'll make separate PRs.   Is this because a file name changed?

**Comment by ahmetb** [comment]
Actually I misremembered, yeah it's because it's not a simple version find-and-replace. I can merge if you reopen.

**Pull request closed without merging**
