### PR TITLE
feat: update homepage and uri for kubesec-scan

### LINKED ISSUE #1165: kubectl-kubesec uri update
When installing kubectl-kubesec, the homepage directs towards the repo https://github.com/stefanprodan/kubectl-kubesec and then get forwarded to https://github.com/controlplaneio/kubectl-kubesec.

To avoid confusion, recommend changing the homepage/uri to https://github.com/controlplaneio/kubectl-kubesec for kubectl-kubesec.

### PR DESCRIPTION
**Pull request by denhamparry**
- closes #1165
- update references from steganprodan to controlplaneio within
kubesec-scan

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/kubesec-scan.yaml` is not a straightforward version bump: could not find the old/new version spec in the diff

**Comment by denhamparry** [comment]
I signed it

**Comment by denhamparry** [comment]
I signed it

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/kubesec-scan.yaml` is not a straightforward version bump: could not find the old/new version spec in the diff

**Comment by denhamparry** [comment]
Getting up to speed and finding other legacy issues including not including the LICENSE within the release https://github.com/controlplaneio/kubectl-kubesec/issues/22, looking to close that issue to enable CI build on this PR

**Comment by ahmetb** [comment]
ping me when the tests pass 👍🏼

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/kubesec-scan.yaml` is not a straightforward version bump: change on line `4` does not seem like a version bump: [`-  homepage: https://github.com/stefanprodan/kubectl-kubesec`]

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/kubesec-scan.yaml` is not a straightforward version bump: change on line `4` does not seem like a version bump: [`-  homepage: https://github.com/stefanprodan/kubectl-kubesec`]

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/kubesec-scan.yaml` is not a straightforward version bump: change on line `4` does not seem like a version bump: [`-  homepage: https://github.com/stefanprodan/kubectl-kubesec`]

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/kubesec-scan.yaml` is not a straightforward version bump: change on line `4` does not seem like a version bump: [`-  homepage: https://github.com/stefanprodan/kubectl-kubesec`]

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/kubesec-scan.yaml` is not a straightforward version bump: change on line `4` does not seem like a version bump: [`-  homepage: https://github.com/stefanprodan/kubectl-kubesec`]

**Comment by denhamparry** [comment]
@ahmetb took me a while but I got there.  All tests are now passing :smile_cat:

**Pull request merged**
