### PR TITLE
Add plugin: terminate

### PR DESCRIPTION
**Pull request by xcoulon**
Fixes https://github.com/kubernetes-sigs/krew-index/issues/511

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Comment by xcoulon** [comment]
thanks for your review @ahmetb ! I've applied the changes you requested. Please let me know if you have further concerns.

**Comment by xcoulon** [comment]
> force-rm can (perhaps not so intuitively) actually be a better branding and might be better for discovery (when you're scanning a list of 150 plugins). I am +1 for a name change if it's still possible on the upstream.

thanks for your responses and suggestion with regards to the plugin name. I initially thought about naming it `terminate` as I was dealing with namespaces in `terminating` state, but maybe that `force-rm` or `force-delete` (to match with the current `delete` command) would be better. Just give me a bit of time to think about it ;)

**Comment by corneliusweig** [comment]
Friendly ping. AFAIU there is an open question of plugin naming. Have you thought about how to resolve that?

**Comment by xcoulon** [comment]
> Friendly ping. AFAIU there is an open question of plugin naming. Have you thought about how to resolve that?

yes, I will rename the plugin to `force-delete`. My apologies, I thought I already responded to the proposal. I will try to take care of it soon.

**Comment by ahmetb** [comment]
Closing this PR, feel free to re-submit please. :)
/close

**Pull request closed without merging**
