### PR TITLE
new version v0.14.1 of view-allocations

### PR DESCRIPTION
**Pull request by davidB**

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file `plugins/view-allocations.yaml` is not a straightforward version bump: change on line `28` does not seem like a version bump: [`-    limit, allocatable) as defined into the manifest of nodes and running pods,`]

**Comment by davidB** [comment]
I fix the typo as requested in the previous PR https://github.com/kubernetes-sigs/krew-index/pull/1194#pullrequestreview-633019782

**Review by corneliusweig — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
