### PR TITLE
Update virt.yaml for v0.19.0-rc.0

### PR DESCRIPTION
**Pull request by dhiller**

### CODE REVIEW

**Comment by corneliusweig** [comment]
Can we delay until this version becomes stable? Or is there an urgent need to update to an rc version?

**Comment by dhiller** [comment]
@corneliusweig my fault, sorry for disturbing.

**Comment by corneliusweig** [comment]
I wouldn't call it fault. Nothing really happened. And it's highly appreciated that you take care of keeping the plugin up to date! :+1:

**Comment by dhiller** [comment]
Yes, it was one, as there already is a v0.19.0 which I had overlooked.

**Pull request closed without merging**
