### PR TITLE
Add kubectl-aks plugin v0.1.0 (Manages AKS clusters from kubectl)

### PR DESCRIPTION
**Pull request by C123R**
-----

**Checklist for plugin developers:**

- [X] Read the [Plugin Naming Guide](https://github.com/GoogleContainerTools/krew/tree/master/docs/NAMING_GUIDE.md) (for new plugins)
- [X] Verify the installation from URL or a local archive works (`kubectl krew install --manifest=[...] --archive=[...]`)

Tested with krew install locally:

```bash
$ kubectl krew install --manifest=aks.yaml
Installing plugin: aks
CAVEATS:
\
 |  In order to access AKS clusters from kubectl, you need azure service principal.
 |  You can find more information and documentation at https://github.com/C123R/kubectl-aks.
/
Installed plugin: aks
```

### CODE REVIEW

**Comment by ahmetb** [comment]
If you’re using a vendor’s name, the plugin should come from their official repositories.
If you work at AKS, please create a repo in the official org for this, or convince AKS to do this.

**Comment by C123R** [comment]
Oops...
@ahmetb  Okay, have some contacts. Will try to convince them. Hope this works out :(

**Comment by ahmetb** [comment]
Thanks, that would be preferable.
I’ll close this until then.
/close

**Pull request closed without merging**
