### PR TITLE
Update flytectl homepage

### PR DESCRIPTION
**Pull request by EngHabu**
flytectl moved from lyft/ org to flyteorg/

### CODE REVIEW

**Comment by ahmetb** [comment]
:robot: _Beep beep! I’m a robot speaking on behalf of @ahmetb._ :robot:

-----

This pull request **does not** seem to be a straightforward version bump. I'll have a human review this.

_Why wasn't this detected as a plugin version bump:_

>file plugins/flyte.yaml is not a straightforward version bump: could not find the old/new version spec in the diff

**Comment by EngHabu** [comment]
Signed

**Comment by ahmetb** [comment]
No update to the download paths?

**Comment by EngHabu** [comment]
github sets up redirects... so these continue to work.
The CI will send an update to the plugin with every new releases from the new path... is that ok?

**Comment by ahmetb** [comment]
Sure but if paths change it'll require manual approval.
/lgtm
/approve

**Pull request merged**
